### ISSUE TITLE
Planning Documentation

### ISSUE THREAD

**Issue by seve** [ottomated/CrewLink#1]
Hi there, is there any roadmap or ticket banks so that the community can help further the progress of the mod?

**Comment by ottomated** [comment]
There isn't yet. Can you suggest a template to use to set that up?

**Comment by seve** [comment]
You might want to create issues for all the features/bugs/tweaks you plan on putting into the mod.  Then you could make a public/private [github project](https://github.com/features/project-management/), to manage the process of each issue.  This also allows the community to upvote and downvote features to give you an idea of what should be prioritized. This paired with milestones which will show targeted releases for issues will help determine the future of the mod.  You could also just draw out a [roadmap.md like this ](https://github.com/moby/moby/blob/master/ROADMAP.md)

**Comment by ottomated** [comment]
Done! https://github.com/ottomated/CrewLink/projects/1

**Comment by seve** [comment]
Lookin good!
