### ISSUE TITLE
Couldn't fetch...

### ISSUE THREAD

**Issue by agrinber** [ottomated/CrewLink#101]
I know there was some talk about this on the twitter thread, but when I try to run the app I get the "couldn't fetch the latest game offsets" error. I am not running the beta version of among us, so I'm not sure what else could be the error. 
![image](https://user-images.githubusercontent.com/75461834/101116105-51963900-3599-11eb-90e6-bffb17547a9a.png)

**Comment by PapaWorst** [comment]
Me and a bunch of my friends are having the same issue tonight.  One of our friends can get in, but the rest of us get this error message.  We all have the same version of Crewlink and Among Us

**Comment by Cjmugen** [comment]
Some of my friends are still having this issue

**Comment by PapaWorst** [comment]
This is happening again
