### ISSUE TITLE
Not recognizing game 

### ISSUE THREAD

**Issue by yjiggly** [ottomated/CrewLink#106]
I downloaded crew link and everything is fine until I click open game and among us opens but crew Link is still saying waiting for among us and open game. i also tried deleting my app data and it still wont work how do i fix this?

**Comment by yjiggly** [comment]
i also tried deleting my app data and it still wont work

**Comment by tdwafl** [comment]
Is your among us set to reg client, not beta?

**Comment by DispatchCommit** [comment]
Are you on a cracked copy of the game?

**Comment by yjiggly** [comment]
i am on the regular game(no beta programs), and i purchased it through steam.

**Comment by DispatchCommit** [comment]
Make sure you're not running steam or the game as admin. Also try running CrewLink as admin, although right now since 12.3 just released it'll be broken.

**Comment by CheckisCheck** [comment]
Its because the new among us update

**Comment by DispatchCommit** [comment]
This issue was opened prior to the update @CheckisCheck

**Comment by yjiggly** [comment]
alright, so should i just wait for a new release?

**Comment by yjiggly** [comment]
i have downloaded the new version and still have the same problem :(

**Comment by yjiggly** [comment]
got it too work! i just ran it as admin

**Comment by cameronpfs** [comment]
The reason is because the raw IP will not work. Try using the server URL that will fix it.

**Comment by venmomaxnru** [comment]
Yo i got crewlink for my cracked among us but when I'm in a game it doesn't show a code it just shows MENU on crewlink. How can i fix it?

**Comment by qt-qtpepe** [comment]
I have the cracked among us it just says menu when i open it up

**Comment by wincon06** [comment]
What do I do when it says this file dose not have an associated app with it
