### ISSUE TITLE
Robotic audio when people join lobby, change cosmetics, change from alive to dead

### ISSUE THREAD

**Issue by ottomated** [ottomated/CrewLink#11]
This is likely due to excess CPU usage in https://github.com/ottomated/CrewLink/blob/master/src/renderer/Avatar.tsx when loading images.

**Comment by hugeblank** [comment]
By robotic audio do you mean it sounds similar to when you speak into a box fan? If so I think it extends beyond image loading, and is more so to do with audio driver complications.
