### ISSUE TITLE
Doesn't Pick Up Voice After 2 Games

### ISSUE THREAD

**Issue by chickentendieboi** [ottomated/CrewLink#112]
My friends and I tried playing Among Us with the crew link and it was working for about two games. It would pick up the green circles when anyone was talking period but then after the two games you couldn't hear anyone the circles around everyone's buddy were red. I ended up re-downloading it and it worked again but we haven't played another game yet because no one elses seems to work.

**Comment by ottomated** [comment]
Ctrl R
