### ISSUE TITLE
[suggestion] Crack/Emulator version of the game support

### ISSUE THREAD

**Issue by LUKISO2** [ottomated/CrewLink#115]
Hi,

I was wondering if there is any way, how to connect the app to a cracked, or an emulated version of Among Us.

For example, if the app cant detects a Steam version of Among Us, let the user chose 1of the running programs, to tell the program, where to look for the running game.
Or let the user direct it to the folder with a cracked AmongUs.exe file.

I don't know if you can pull data from the emulated version of Among Us (BlueStacks, Nox, etc...), but it would be better than the crack version, for obvious reasons.

Thank you for your response!

**Comment by unix-system** [comment]
Why would this mod support piracy and theft? It's $5, pay the money.

**Comment by LUKISO2** [comment]
Thats why I mensioned the emulated version too, then it isnt a piracy or theft. Iam just aware, that the emulated version isnt maybe possible to do, thanks to the fact, that it is a emulator and maybe its not giving the necessary info for the mod to work.
And peaple are not willing to pay anything for anything, if they can get it for free... (most of them)

**Comment by ottomated** [comment]
Nomegalul
