### ISSUE TITLE
I can`t use crewlink

### ISSUE THREAD

**Issue by PaprykarzP** [ottomated/CrewLink#116]
![error2](https://user-images.githubusercontent.com/75502710/101211681-d788b180-3677-11eb-916f-cf95a6da9780.PNG)
![error 1](https://user-images.githubusercontent.com/75502710/101211682-d8b9de80-3677-11eb-863d-63728558bfbf.PNG)

I tried Enable crewlink but without successfully getting the error "Couldn`t fetch the latest game offsets from server: http://54.193.94.35:9736/2020.12.3.yml. This might be because you are on unsopported version of among us. Restart the app after you fix this. "When I press ok, I only get a button that says" Relaunch app ".
I have the original one among us purchased on steam. I tried to enable the beta, reinstall and install but it doesn't do anything. I have searched without a successful solution. Can someone please help me?

**Comment by PaprykarzP** [comment]
My among version is "v2020.12.3s"

**Comment by Gaelan** [comment]
A new version of Among Us came out and the mod hasn't updated yet, see https://github.com/ottomated/CrewLink-server/issues/9
