### ISSUE TITLE
MENU SCREEN

### ISSUE THREAD

**Issue by PureIzBad1** [ottomated/CrewLink#118]
When i join a game (this is the same as my friends) it just says where in the menu on crewlink

**Comment by xenoguy** [comment]
among us update happened today, so the offsets for the game hook need to be updated.

**Comment by Tobin801** [comment]
When will that get fixed? Me and my friends are having the same issue.

**Comment by MrLuxxe** [comment]
Yeah when will this be fixed?

**Comment by DispatchCommit** [comment]
Fixed in v1.1.4
