### ISSUE TITLE
The same two people can only hear eachother and no one else

### ISSUE THREAD

**Issue by Nu7M3g** [ottomated/CrewLink#119]
Hey!

There are 6 people in our lobby, four of us can hear eachother but not the other two, the other two can hear eachother and not the four others.

Any ideas?

**Comment by xenoguy** [comment]
the app uses webrtc to connect people i think, have people run this test and see if it works or not:

https://test.webrtc.org/

**Comment by SizableShrimp** [comment]
Seems to be similar/duplicate of #47

**Comment by ottomated** [comment]
Duplicate of #47
