### ISSUE TITLE
Super improbable network issue

### ISSUE THREAD

**Issue by steven-tan** [ottomated/CrewLink#12]
Hey there, I apologize in advance for how weird this report is, but on the off chance it's not just something unique to our network, I thought I should share.

My son tried this mod (which all his friends use) and it seemed to work okay. However, upon hitting the "Play Again" button in Among Us while the mod was running, our network connection (not just his, but the whole house) would cut out. We restored network by resetting our PACE 5268AC modem (provided by AT&T Internet), and things would be fine again.

I thought this HAD to just be a coincidence, but my son swears he repeated the process at least 5 times, and every single time, internet would cut out when hitting "Play Again" while the mod was running.

By the time I started looking into it, he had already deleted the executable from his computer and said he didn't need to use it. He played a regular Among Us game (this time without CrewLink on his computer) and had no issues when hitting the "Play Again" button.

Again, I know this sounds super-weird (bordering on impossible), but I thought I'd submit anyway just in case someone else is experiencing it, or if the dev is aware of any network-level operations (maybe something that could result in a blast of UDP or some whacky UPNP type thing that might cause a router to freeze up. (I'm technical enough to know how unlikely this is, but also technical enough to have seen some insane/unexpected things in my day heh)

**Comment by ottomated** [comment]
That sounds insane. I can't imagine it is anything but a coincidence. Maybe if it's an old modem, the rapid disconnection and reconnection to WebRTC somehow crashes your router? I have no clue.

**Comment by steven-tan** [comment]
Absolutely agree it sounds insane, trust me - I had to talk myself into even posting this.

It's definitely an old modem (but probably also still the most widely deployed modem for AT&T internet). It is hot garbage, and does tend to need rebooting monthly, but not 5 times in one evening. Never even close.

Closing this issue now, thanks for humoring me anyway heh.

**Comment by steven-tan** [comment]
Quick follow-up on this, being still somewhat dubious, I conducted the experiment while my kid was playing Among Us, and once again, he was able to reproduce tonight by hitting the "Play Again" button. Totally crazy.

Not a big deal, as he's just agreed to stop using crewlink until we get a new modem (if AT&T will let me switch models), but I just wanted to share.
