### ISSUE TITLE
Crewlink not recognizing among us.

### ISSUE THREAD

**Issue by sashman2013** [ottomated/CrewLink#120]
My friend and I both have the same problem with crewlink: it recognizes when the game opens, but it does not recognize when you go into a lobby. Is there a step we didn’t do you when updating crewlink?

**Comment by troywoy** [comment]
My error is as follows:
```
You are on an unsupported version of Among Us: 2020.12.3.

Restart the app after you fix this.
``

I assume this means a new CrewLink version needs to be released to support this Among Us version?

**Comment by sashman2013** [comment]
I have the updated version of both crewlink and among us, but the crewlink is currently not recognizing when I’m in a lobby

**Comment by troywoy** [comment]
Okay I think I got it (my issue at least). I redepolyed the latest server code and that seemed to fix it.

**Comment by xenoguy** [comment]
yep, seems the offsets are stored on the server side and need to be updated every time among us is updated.
