### ISSUE TITLE
voice server issue

### ISSUE THREAD

**Issue by micheal-commitsarson** [ottomated/CrewLink#121]
everytime I open it its not working

**Comment by SizableShrimp** [comment]
This gives no information. Please look at some of the existing issues for what problem you are experiencing, or join the support discord and then close this issue.

**Comment by micheal-commitsarson** [comment]
> This gives no information. Please look at some of the existing issues for what problem you are experiencing, or join the support discord and then close this issue.

Can you give me the discord link?

**Comment by SizableShrimp** [comment]
https://discord.gg/QG2KwPWjvj
