### ISSUE TITLE
error message when opening crewlink

### ISSUE THREAD

**Issue by rabbieark** [ottomated/CrewLink#129]
![crewlinkError](https://user-images.githubusercontent.com/75511941/101231879-128ce400-367c-11eb-812e-66ba640dd245.PNG)

I get this message when I try opening among us and crew link
 after I restart crewlink it doesn't recognize game

**Comment by WarriorofZarona** [comment]
I get this same message.

**Comment by SomnusXVII** [comment]
same has anyone figured it out yet?

**Comment by opti21** [comment]
Too many people are trying to use the public server, Try setting up your own using: https://github.com/ottomated/CrewLink-server

**Comment by ASOwnerYT** [comment]
I'm having the same issue, would be great if they can upgrade their servers

**Comment by chanwoo321** [comment]
I am still having this issue after hosting my own server

**Comment by opti21** [comment]
Is it giving the same exact error? are putting your app's heroku url in the voice server setting and not the one it gives on the webpage?

**Comment by reoguy55** [comment]
I'm hosting my own server using Docker and I'm getting the same error still. I've changed the app voice server settings to be the new server URL.

**Comment by nordiago** [comment]
@reoguy55 Is the server's firewall set to accept the CrewLink port? Or are you using a custom port?

**Comment by RabidPoodle** [comment]
Same here, I deployed on heroku and put in the url it gave me on the page and I get the error couldn't get latests offsets and ETIMEDOUT

**Comment by opti21** [comment]
@RabidPoodle you put in the actual app url (i.e. appname.herokuapp.com)

**Comment by reoguy55** [comment]
> @reoguy55 Is the server's firewall set to accept the CrewLink port? Or are you using a custom port?

I'm not sure how I would change the firewall settings, I'm still a complete Docker noob. Could you elaborate on how to do this?

I initially tried hosting the server with the default 9736 port but I've also tried a custom port (8889) and I received the same error.

**Comment by RabidPoodle** [comment]
@opti21 thank you! I thought I was supposed to put in the url with all the number that the webpage gave me

**Comment by nordiago** [comment]
@reoguy55 That would depend on the server (OS, firewall type). Or are you running Docker on your computer?

**Comment by reoguy55** [comment]
I'm running Docker Desktop on my computer, and ran the server via Terminal to start it. I can check to make sure that Windows Defender isn't blocking Docker/Crewlink.
