### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by samizayn4life** [ottomated/CrewLink#131]
![Error](https://user-images.githubusercontent.com/75516048/101234671-3816ef00-3676-11eb-81db-fcaab9bbb711.PNG)

I get this image and crewlinks tells me to wait a couple days for the apps to be working, yet some of my friends said there's work fine. What should I do?

**Comment by guttertrashd** [comment]
You have to wait until someone updates crewlink again before you can use it. It works for your friends because they haven't updated Among Us yet.
