### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by DusilB** [ottomated/CrewLink#132]
Can you make the listen distance hardcoded value adjustable in the client or sourced from a config file?

`
if (gain.gain.value === 1 && Math.sqrt(Math.pow(me.x - other.x, 2) + Math.pow(me.y - other.y, 2)) > [make this configurable]) {
		gain.gain.value = 0;
	}
`

**Comment by mrhyde1st** [comment]
For that to work, it would only have to be able to be set only by the Host, can't have some users setting it higher or lower independently as otherwise some users could set theirs a lot higher than others in the same game.
