### ISSUE TITLE
whenever i open the app, i get this message

### ISSUE THREAD

**Issue by zbeshore** [ottomated/CrewLink#134]
not sure what is happening whenever i open the app, i get this message. not sure what is going on. i do not think it is my server since it has worked in the past.
![Untitled](https://user-images.githubusercontent.com/75518525/101236305-ff324680-3684-11eb-9d00-db7ea02fefa4.png)
hopefully this picture works

**Comment by nordiago** [comment]
@zbeshore Looks like you're missing the "h" in "http://..."

**Comment by zbeshore** [comment]
yea, but i cannot change anything, when i try to type the h in, nothing happens, i cannot even change the IP at all
