### ISSUE TITLE
Can hear some people but cant hear others

### ISSUE THREAD

**Issue by AyyBae** [ottomated/CrewLink#136]
Idk why it does this please help

**Comment by mrhyde1st** [comment]
Was working ok for me...have you tried some simple options:

- Had People connected to the same server in the app?
- Were their sound devices correct in their settings?
- Were the other users on Push-to-talk or Voice Activity?  If the former were they pressing the Talk button?
- Had they deafened themselves, which also mutes themselves?
- Was this when stood next to them, or had they walked away from you?

**Comment by AyyBae** [comment]
> Was working ok for me...have you tried some simple options:
> 
> * Had People connected to the same server in the app?
> * Were their sound devices correct in their settings?
> * Were the other users on Push-to-talk or Voice Activity?  If the former were they pressing the Talk button?
> * Had they deafened themselves, which also mutes themselves?
> * Was this when stood next to them, or had they walked away from you?

Everyone else could hear them but me, I can hear like 2-4 people but i cant hear anyone else. Everyone else can hear each other

**Comment by dadodasyra** [comment]
Same, I had the same problem when I did my tests, even on the old version. Some people heard, some other people heard. For example, let's take letters (there is A B C D E F).
A could hear B C and D, B could hear only A C and not D, C could hear no one, D could hear E F and A. Every time someone restarted he would hear other people. But overall it never happened that everyone got along at the same time. (We were in the lobby)

**Comment by ottomated** [comment]
Duplicate
