### ISSUE TITLE
Other can hear other people, while other cant hear other

### ISSUE THREAD

**Issue by Dvckfield** [ottomated/CrewLink#140]
Some people can't hear other people, and it's random for everyone. We tried EVERYTHING and NOTHING is working. This is annoying and I searched over all the issues and it wasn't solved, and I know it's a duplicate but I need an answer because it's a sick concept for among us. Will the next patch fix it or something?

**Comment by ottomated** [comment]
If you know it's a duplicate then use the issue tracker properly and leave a comment with helpful information on the existing issue.
