### ISSUE TITLE
Unsupported version of Among Us

### ISSUE THREAD

**Issue by Drake62610** [ottomated/CrewLink#142]
**Bug report**

It seems that the later Among Us update that happened 2 days ago have broken Crewlink, here is my error message showing when i try open that name with Crewlink.

![image](https://user-images.githubusercontent.com/27460666/101262446-1e8daa00-373f-11eb-9e8f-33eeb408607d.png)

**Comment by C0an** [comment]
Yeah having the same problem, you’ll have to give it a few days before @ottomated updates it server-side
