### ISSUE TITLE
App not supported with last version among us

### ISSUE THREAD

**Issue by acotillard** [ottomated/CrewLink#147]
![Capture](https://user-images.githubusercontent.com/2798016/101265851-43d3e580-374a-11eb-84db-f87e69ae7941.PNG)

**Comment by varedz** [comment]
Game just updated, he's not on to update pointers right now.

**Comment by acotillard** [comment]
with  v1.1.4

**Comment by varedz** [comment]
@ottomated 
MeetingHud: 0x1BE0CB4
AmongUsClientOffset: 0x1BE1074
GameDataOffset: 0x1BE0BB8
GameStartManagerOffset: 0x1B5AB00

**Comment by allyoop92** [comment]
getting the same error message, so basically just wait it out until it works again?
