### ISSUE TITLE
You are on an unsupported version of Among Us : 12/5/2020

### ISSUE THREAD

**Issue by dwobbie** [ottomated/CrewLink#151]
Hello! It was working perfectly fine this morning and then it showed that error message followed by :" Make sure that the Voice Server is correct in the settings and you are using the latest version of Among Us. If there was a recent update, CrewLink might not work for a few days." Not sure what's going on, is the same thing occurring for anyone else? Thank you!

**Comment by Loganwassnagged** [comment]
Yeah I am having the same problem and I don't think among us has updated cuz i kept checking and it was working a few mins before it happened. lol

**Comment by tykazzz** [comment]
https://github.com/ottomated/CrewLink-server/issues/20
