### ISSUE TITLE
Whenever I hit Open Game it gives me an error. It's happening to my friends too.

### ISSUE THREAD

**Issue by MasterAden52** [ottomated/CrewLink#154]
![error](https://user-images.githubusercontent.com/44624610/101269854-10d92400-3741-11eb-9dab-722d2b1baf5d.png)

**Comment by MeowMixSSB** [comment]
same here, hope it gets resolved soon

**Comment by smallcows635** [comment]
same

**Comment by NCGamer2004** [comment]
same

**Comment by DanielleM565** [comment]
I had the same issues tried the app the next day got a different error particularly
an uncaught type error exception... so I closed the app and then tried to rerun it but instead I right clicked and ran it as a administrator and suddenly boom it worked. I'm not a super savvy back-end dev more front end but I think for the devs that built this there's a permissions somewhere error here are the screenshots of the errors I ran it to the second time 
![crewlink-bug2](https://user-images.githubusercontent.com/26804376/101271396-8643f500-373f-11eb-9ade-d211472b3528.PNG)

![crewlink-bug3](https://user-images.githubusercontent.com/26804376/101271400-8a701280-373f-11eb-8618-891a89c53ea5.PNG)

**Comment by JohnsonJesse** [comment]
![image](https://user-images.githubusercontent.com/75556677/101272012-98289680-3745-11eb-92ac-acef3bcade8c.png)
Same issue, it is persisting no matter how many times I restart the CrewLink application or reinstall it, it either happens right as I launch it, or when I try to host/join a game. Do we know if there is a fix yet?

**Comment by ottomated** [comment]
Private server

**Comment by RaticalSurfer** [comment]
> Private server

I have made one and I get the same error no idea what's causing it.
