### ISSUE TITLE
Crewlink not compatible with newest update 

### ISSUE THREAD

**Issue by queeenn** [ottomated/CrewLink#156]
![image](https://user-images.githubusercontent.com/37917759/101272278-f8b8d300-3747-11eb-98b6-25e4cc37f0d7.png)
This message is shown whenever I attempt to open Among Us through crewlink. Among Us opens, but the Crewlink GUI doesn't.

**Comment by AtelDaKing** [comment]
Yes it has said CrewLink May not work for a few days after new updates
