### ISSUE TITLE
Having no mic connected makes you unable to hear anyone (everyone has red ring)

### ISSUE THREAD

**Issue by trollbreeder** [ottomated/CrewLink#166]
When you have **no microphone connected**, like i do, it throws an error every time it reloads (e.g. when changing settings), and shows everyone in the lobby with a **red ring**, even if they are **using crewlink** and are **connected properly,** and even if your crewlink is **otherwise working correctly.** Others will also see you with a red ring. This means that you **cannot hear anyone talking at all.**

It should interpret having no mic as always absolute silence, instead of throwing a fit and dying.

**Comment by ottomated** [comment]
Won't fix. Microphone is necessary to establish a rtc connection.
