### ISSUE TITLE
connect ETIMEDOUT 

### ISSUE THREAD

**Issue by BushThePresidant** [ottomated/CrewLink#169]
![image_2020-12-06_154020](https://user-images.githubusercontent.com/75586573/101291787-58ab8a00-37d9-11eb-8257-d8806b9801ec.png)

**Comment by HazimAr** [comment]
i have the same issue the dev just needs to update the offsets for the new version

**Comment by vrnagy** [comment]
It's an issue with the free server. (Probably the high number of active users or some software issue)
Nothing to do with the offsets. If You want You can host Your own server to use.

**Comment by Linetorek** [comment]
I have the same thing on my own server.

**Comment by zbeshore** [comment]
i host my own server and get the same issue

**Comment by vrnagy** [comment]
I did not experience any issue like this with self-hosted server. We had a multo-hour session with the latest Among US version and worked fine. The IP in the error message is the free server hosted by the creator. If You have the same issue with Your server ip / domain name, it's a different issue.

**Comment by Melsubbink** [comment]
The servers are down, everyone who is experiencing this via the default Voice Relay server gets this, because the server is down.
Selfhosted servers don't have this.

**Comment by Melsubbink** [comment]
If you want to play without these kind of problems, you can consider hosting your own voice relay server, with the help of the creators' [CrewLink-server repo.](https://github.com/ottomated/CrewLink-server)

**Comment by Melsubbink** [comment]
Dont forget to copy the link to your custom server in the CrewLink settings, under "Voice Server". Your CrewLink is currently still connected to the default server: http://54.193.94.35:9736 .

**Comment by Robinvg12** [comment]
im also hosting another public server you can also use this: 
https://public-crewlink.glitch.me
