### ISSUE TITLE
v 1.1.4 error game offsets, no new Among Us Update

### ISSUE THREAD

**Issue by JacobSchwitzer** [ottomated/CrewLink#185]
Hi, I'm running crew link v 1.1.4 for the first time and I keep getting the game offsets error. However, I don't have an update for Among us that would fix this error. I've attached the error as an image.
![crewlink error](https://user-images.githubusercontent.com/37703789/101292537-a625f800-37d5-11eb-8f3c-67b9069e5844.PNG)

**Comment by vrnagy** [comment]
It's not an offset issue, it's a server issue. See issue #169

**Comment by Robinvg12** [comment]
yeah the public servers are down

**Comment by JacobSchwitzer** [comment]
Ohhhh ok so its the default voice server. Any suggestions for creating my own voice server then?

**Comment by vrnagy** [comment]
Check out the https://github.com/ottomated/CrewLink-server repository. It has documentation about how to host Your own server

**Comment by Robinvg12** [comment]
i made a server with glitch so you can use this i guess: https://public-crewlink.glitch.me

**Comment by JacobSchwitzer** [comment]
Thanks for the suggestions! I really appreciate it!
