### ISSUE TITLE
Allow program to run the latest Among Us on our own?

### ISSUE THREAD

**Issue by unbecomingname** [ottomated/CrewLink#187]
(For clarification I know nearly nothing about coding) I've seen that the Offsets in the Crewlink server were updated for the latest Among Us versions, but the normal Crewlink still can't support them? Is it possible to allow the program to support the newest version or should I try figuring out how to revert to a version of Among Us that is still supported by the program?

**Comment by Ornamus** [comment]
If you launch Crewlink after Among Us is running, it pulls the offsets from the server and works fine on the current game version (`2020.12.5`).

**Comment by unbecomingname** [comment]
![image](https://user-images.githubusercontent.com/20285616/101297113-345da680-37f5-11eb-9120-53d3f62322af.png)
Tried that, still getting the same error code. I'm running the server through Docker if that helps with anything

**Comment by stephqq** [comment]
you'll need to update your server with the latest from the server repo

**Comment by unbecomingname** [comment]
I'm running the server using the command on the server repo, "docker run -d -p 9736:9736 ottomated/crewlink-server:latest" and tried re-running it doing the same command. Is there a different way of running this through Docker or am I just not doing this right?

**Comment by OiYouYeahYou** [comment]
@unbecomingname run `docker pull ottomated/crewlink-server:latest`, which will get the latest version of the server. Then `docker ps` to find the name of the running version then kill it with `docker stop <name of container>`. Then run that command.

**Comment by unbecomingname** [comment]
@OiYouYeahYou That worked, thank you so much! Is it possible to pull the files and put them in a filepath? My friends don't have docker cos I'm running the server so I was wondering if they can update the offsets without installing Docker. If not it's fine, but thank you for the help

**Comment by Ornamus** [comment]
@unbecomingname That command updates the server, which is what sends the offsets to the clients. Your friends shouldn't need to install docker or do anything besides connect to your updated server.

**Comment by OiYouYeahYou** [comment]
@Ornamus They were talking about injecting the offsets into the application, ie adding to cache manually.

@unbecomingname the app at this time doesn't support it

**Comment by blur26** [comment]
i’m still confused on how you guys were able to solve the problem with it saying “you are on an unsupported version of Among Us” I want to fix this but don’t know how to. How can I resolve this issue and use Crewlink and have it working properly.

**Comment by unbecomingname** [comment]
Make sure you're on CrewLink 1.1.4. Try what Ornamus said and run the game first, then run CrewLink and see if that works. If not, make sure that whoever is running the server does the commands that OiYouYeahYou listed. Then whenever that's done try re-inputting their IP/server. I believe the public server takes longer to update, so you should keep it on private servers for now until the public gets fixed
