### ISSUE TITLE
Couldn't fetch the latest game of offsets from the server

### ISSUE THREAD

**Issue by ohReemo** [ottomated/CrewLink#189]
![image0 (1)](https://user-images.githubusercontent.com/75594149/101300890-2152d280-3805-11eb-897c-cea23934a31b.jpg)
This problem happened yesterday and today after me and my friends only playing one game and it happened to all of us.

**Comment by o0purehate0o** [comment]
I'm guessing the server went down. I am also getting the same error code

**Comment by dragonsarecools420** [comment]
I'm getting the same error as well... is there any way we can host the offsets on our own computers?  That way we don't have to rely on ottomated's servers.

**Comment by Ornamus** [comment]
> I'm getting the same error as well... is there any way we can host the offsets on our own computers? That way we don't have to rely on ottomated's servers.

https://github.com/ottomated/CrewLink-server has instructions for hosting your own Crewlink server, which includes the offsets.
