### ISSUE TITLE
"unsupported version of among us: 2020.12.5." Error message

### ISSUE THREAD

**Issue by Crios2837** [ottomated/CrewLink#194]
"unsupported version of among us: 2020.12.5." keeps popping up on my computer after opening the app approximately 15 seconds later. I never used betas, computer will automatically upload new updates, and I know my internet connection is good. I don't know what the issue is but any assistance will be grateful.

**Comment by fictionaldeity** [comment]
you gotta wait for them to post an update to crew link or downgrade to an older version of among us

**Comment by BrittBrittTv** [comment]
I tried downgrading and it would immediately update to the new version.

**Comment by JannisCCC** [comment]
For me, 20.12.5 is working

**Comment by AtelDaKing** [comment]
Yeah it was working but it stoped working for some reason
