### ISSUE TITLE
every new update..and cant use it at all because of this issue

### ISSUE THREAD

**Issue by Hyp3r10** [ottomated/CrewLink#197]
![image](https://user-images.githubusercontent.com/75603613/101317704-a0a3ce80-3824-11eb-93d1-e008db15004a.png)

**Comment by Hyp3r10** [comment]
does this every new update and cant use the game mod at all.

**Comment by SsjSilentTV** [comment]
getting the same issue, only just got it... it launched the game but then gone showing the same error every time
