### ISSUE TITLE
Auto offset updating

### ISSUE THREAD

**Issue by QPixel** [ottomated/CrewLink#20]
I've been looking through some other among us "tools". I believe it is possible for CrewLink to auto-update offsets.  I also think that CrewLink should pull the offsets from the GitHub repo instead of the CrewLink server.

https://github.com/denverquane/amonguscapture/blob/bedaa915995408325f7d42a21c55e7f6a593836b/AUOffsetManager/OffsetManager.cs

**Comment by ryantheleach** [comment]
Crewlink already does auto-update, it's just currently doing it from the voice server specified in your settings, e.g. crewlink server.

Other then pulling from github, I don't really see what OffsetManager does different?

**Comment by QPixel** [comment]
I didn't fully read the code that the repository had. This was more for otto. I need to actually find an auto offset finder.

**Comment by QPixel** [comment]
Closed b/c I am stupid
