### ISSUE TITLE
Sound Issue some Player can talk, some not - pls dont close

### ISSUE THREAD

**Issue by StevezLife** [ottomated/CrewLink#202]
Can you pls answer to this problem and not close it and say its the same like this or that post. That doesnt help.

Some of my friends cant use the proximity chat. They hear the half of the lobby but not all. And one half doesnt hear them too.

Whats wrong? We tried everything. Crewlink Options, PC Sound Options, PC Administration Options.

Pls help

**Comment by vrnagy** [comment]
The WebRTC protocol used by CrewLink is peer to peer and sometimes with NAT or too strict firewall the peers can't connect to each other so they can't talk. There is an ongoin pull request regarding this ( #149 ) which add supports for TURN servers to overcome this limitation. However there is one catch. You have to host Your own TURN server, which is basically not hard at all.

**Comment by MaorMizrachi123** [comment]
how do you do that?

**Comment by MaorMizrachi123** [comment]
can you send a video that explaine that?

**Comment by StevezLife** [comment]
Is there no other solution? Im not that good in stuff like that.

**Comment by frymezim** [comment]
As you can see #143 hasn't been merge yet.

**Comment by TheSpringBoy** [comment]
@StevezLife I can recommand you guys just to try reload the program when youre all in.
Reloading it by pressing Ctrl+R (control and R in the same time).

**Comment by vb-03** [comment]
I've solved this for now by enabling "Gamer Mode" in a friend's router that was having this issue

**Comment by ottomated** [comment]
Closed. Duplicate.

**Comment by ottomated** [comment]
Just comment on the other issue.

**Comment by ChaoticWeevil** [comment]
@ottomated which other issue?
@vrnagy how would I host a custom TURN server?

**Comment by Phelms215** [comment]
@ChaoticWeevil  if you are hosting a CrewLink-Server in docker you can use CoTurn. https://hub.docker.com/r/instrumentisto/coturn.
