### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by RockiBurns** [ottomated/CrewLink#203]
For accessibility reasons I primarily play on an Android device. I would love to be able to use Crewlink to have proxy chat games with friends on PC. I would be willing to purchase such an app

**Comment by Tothas** [comment]
Same, I have friends who play but don't have a pc. This would be great

**Comment by Lurzapps** [comment]
react native build?

**Comment by fbnz156** [comment]
Because of the way memory isolation works in Android, this will be practically impossible to do, especially without root. However, an alternative could be developed using screen pixels, though I suspect this would drain the battery too much.

**Comment by ralthenn** [comment]
Because of the way a crewlink works, it does not require access to the main game anyways. It acts as a among us client that talks to all the instances, not just the local one.
