### ISSUE TITLE
Host can be heard by everyone all the time 

### ISSUE THREAD

**Issue by RockiBurns** [ottomated/CrewLink#204]
The host could be heard by everyone, even when they were on the opposite side of the map from the host. This only happened to the host. Starting a new lobby after closing both the game & Crewlink corrected the issue. This happened after multiple games

**Comment by ShayminKeldeo421** [comment]
Had this issue too, explains a lot haha

**Comment by TheSpringBoy** [comment]
Hi,
to fix this issue just go to the CrewLink and press Ctrl+R (control and R in the same time).
It will reload the software and will fix the issue.
I can recommand that the host will do it first and if it wont help so the other players will do it

**Comment by ottomated** [comment]
Duplicate

**Comment by TheSpringBoy** [comment]
@ottomated If you want me to help you with closing and answering peoples Issues (only the Issues, and duplicates) I would love to do that.
