### ISSUE TITLE
Voice Server down for now. I opened one by myself. address in the comments!

### ISSUE THREAD

**Issue by TheSpringBoy** [ottomated/CrewLink#207]
Hi,
currently I cant use the software and when trying to join the server address (http://54.193.94.35:9736/ and https://crewl.ink/) it doesn't work.

**Comment by nimrodgans** [comment]
@TheSpringBoy I think it's related to the latest update, same here

**Comment by Cykl0pS** [comment]
i literally played a game it worked fine and after the game finished it stopped working

**Comment by ioki2622** [comment]
Same issue. I played the game once and then it stoped working

**Comment by loppe17** [comment]
Same! I hope it gets fixed...

**Comment by TheSpringBoy** [comment]
It can be because the update I dont really know...
If you want for now to play I opend by myself an server in amazon for free.
feel free to use it until the public server will be back.
Server Address:
http://aqueous-bastion-56129.herokuapp.com/
![image](https://user-images.githubusercontent.com/75606783/101401868-9e507b80-38db-11eb-85cd-98b8e238cd7a.png)

you can put in in the setting. by pressing the icon in the left.
than scroll down and in the Voice Server line. delete the address and put mine.

The public server address: http://54.193.94.35:9736 or https://crewl.ink/
