### ISSUE TITLE
User not able to connect. "Waiting for Among Us"

### ISSUE THREAD

**Issue by Angziety** [ottomated/CrewLink#213]
I apologize if this issue was already brought up. I have created my own private server, and have about 20 people that can connect and use the app just fine, no issues. I have one user that when attempting to connect, he just gets the message "Waiting on Among Us". I have ensured he is on the same version of among us as we all are. He isn't opted into the beta. He is able to connect to the IP address I have setup for the server over the port I set, just getting the "Waiting for the Among Us" message. Any thoughts?

**Comment by ottomated** [comment]
> I apologize if this issue was already brought up

There's a search bar dude. Closing as duplicate.

**Comment by Angziety** [comment]
And the other responses in the search bar didn't work.
