### ISSUE TITLE
Couldn't fetch the latest game offsets 

### ISSUE THREAD

**Issue by litalien02** [ottomated/CrewLink#216]
Having the following error 

Couldn't fetch the latest game offsets  from the server: http://54.193.94.35:9736//2020.12.5.yml. Error connect EMTIMEDOUT 54.193.94.35:9736

**Comment by JustPokii** [comment]
i have the same problem

**Comment by SacraAnima** [comment]
I have the same problem as well, I've tried re-installing, installing an older version. Nothing worked

**Comment by Clarce** [comment]
you just have to wait till they update the offsets

**Comment by Claue-roe** [comment]
would it be fix if we do private servers?

**Comment by Ornamus** [comment]
> would it be fix if we do private servers?

Yes, the server software has the up-to-date offsets, so any new private servers (or any private servers that have updated) will work just fine with the current version of the Among Us & Crew Link.
