### ISSUE TITLE
Can only hear certain crewmates

### ISSUE THREAD

**Issue by FeatherJo** [ottomated/CrewLink#218]
I have launched Among Us and the Proximity chat and I am only able to hear one person out of all of the others that are connected to our server. I have tried uninstalling and reinstalling both among us and proximity chat but the problem still persisted. Any suggestions on how to fix this? out of the six people in my group, I'm the only person with this issue.

**Comment by ChaoticWeevil** [comment]
I have this same issue

**Comment by ChaoticWeevil** [comment]
Not sure why it was closed
