### ISSUE TITLE
How about cracked version support?

### ISSUE THREAD

**Issue by ZetCreate** [ottomated/CrewLink#234]
Please?

**Comment by ZetCreate** [comment]
And yes, i don't have 4,99$ :(

**Comment by Phelms215** [comment]
Why waste your time with this question?

**Comment by ZetCreate** [comment]
But, why is cracked version support is bad?
I mean like, more people will be playing, or that's bad?

**Comment by ZetCreate** [comment]
> 
> 
> Why waste your time with this question?

Becasue i can't buy license, lol

**Comment by ZetCreate** [comment]
I currently have 0.36$ on my steam

**Comment by ZetCreate** [comment]
Like, I just wanna try game, when i like it and have money i buy it, like gmod

**Comment by TheSpringBoy** [comment]
Hi,
you can just run the CrewLink and the Cracked Among us.
just open the cracked Among Us as usual, and than crewlink.
dont use the open game button

**Comment by ZetCreate** [comment]
> 
> 
> Hi,
> you can just run the CrewLink and the Cracked Among us.
> just open the cracked Among Us as usual, and than crewlink.
> dont use the open game button

Thanks for your help.

**Comment by axvargas** [comment]
did it work? it didn't work for  me

**Comment by TheSpringBoy** [comment]
It should work..
What is the problem you run into?

**Comment by SixHashTag** [comment]
Mine didn't work as well :(

**Comment by MatadorProBr** [comment]
1 - Using cracked versions of the game is illegal and you can be arrested
2 - Among Us was free on Epic Games
3 - https://github.com/ottomated/CrewLink/issues/623#issuecomment-793888862

**Comment by ZetCreate** [comment]
I'm no longer interested in the among us. But I can say that laws in my country is not illegal and cen't get you arrested so that's why I was interested in pirated version support.
