### ISSUE TITLE
Players with same IP cannot hear each other

### ISSUE THREAD

**Issue by sapkra** [ottomated/CrewLink#242]
Everybody was able hear all players. But those who are in the same household couldn't hear the other one but everyone else.
It might be an edge case in the code or some other problem caused the issue.

Player 1 (can hear all except player 2)
Player 2 (can hear all except player 1)
Player 3 (can hear all)
Player 4 (can hear all)

Player 1 and 2 have the same IP.

**Comment by SaifOh** [comment]
have the local players use the local router IP to connect to instead of their IPv4

**Comment by sapkra** [comment]
I'm not 100% sure what you mean but is there a way to figure it out?

**Comment by SaifOh** [comment]
open cmd -> ipconfig
then have the local players who are on the same network connect to the Routers IPv4 showing for you instead of connecting your Internet's IP.
Routers IP usually start with something like 192.168.x.x

**Comment by sapkra** [comment]
The issue appeared again but with different IPs.
