### ISSUE TITLE
Crewlink not compatible?

### ISSUE THREAD

**Issue by yaboiwastaken** [ottomated/CrewLink#247]
I cant seem to get crewlink to work with the updated version of Among Us. 
But the update was last week, is there anyway to get it to work?

**Comment by yaboiwastaken** [comment]
says Im on an unsupported version of Among us: 2020.12.5

**Comment by Ornamus** [comment]
The current version of CrewLink (1.1.5) is compatible with Among Us version 2020.12.5, you just need to be connecting to an up-to-date voice server. If you're using the default voice server, it may be down or overloaded at the moment - you can try connecting to someone else's voice server or hosting one yourself ([see here](https://github.com/ottomated/CrewLink-server)).

**Comment by Caerpre** [comment]
I downloaded the current version of CrewLink and I am also getting this error. I set up my server with deploy to heroku.

**Comment by TheSpringBoy** [comment]
Hi.
solution in #250

**Comment by fisheggs999** [comment]
I have the same problem. I have uninstalled and reinstalled among us and crewlink many times, changed the voice server, and used every possible solution i could find, but it still says "unsupported version of among us 2020.12.5s"

**Comment by Caerpre** [comment]
Things that worked for me were to run Among Us without launching from CrewLink to initialize the version. Then try running CrewLink as Administrator. Finally make sure you're connecting to a server that's up to date.

**Comment by yaboiwastaken** [comment]
Hey! So I think I figured it out, made my own private server and applied that link in. Seemed to work just fine :D
