### ISSUE TITLE
CrewLink incompatible

### ISSUE THREAD

**Issue by Caerpre** [ottomated/CrewLink#251]
I deployed my own server using heroku. I downloaded the latest CrewLink 1.1.5
Every time I open the app I receive "You are on an unsupported version of Among Us: 2020.11.4"
My Among Us is updated, I've reinstalled it. I'm not on Beta. 
Please advise.

**Comment by TheSpringBoy** [comment]
Hi.
make sure the server is updated and that your amongus is in version 2020.12.5s

if you just want to play, see #250

**Comment by Caerpre** [comment]
I deployed the server just minutes ago so it should be updated to current. 
I tried connecting to the server listed in #250 but that doesn't fix my issue. I still get unsupported version.
I've reinstalled Among Us so it is definitely updated. How can I check version?

**Comment by Caerpre** [comment]
I figured it out. I had to open the game by itself first to initialize which version it was detecting. This is resolved.
