### ISSUE TITLE
Lobby creating on standart server

### ISSUE THREAD

**Issue by ZetCreate** [ottomated/CrewLink#266]
I have Windows 10 Pro, hosted server on Heroku and when i joined game and when trying to create lobby it's creating at standart among us server 
![изображение](https://user-images.githubusercontent.com/48327170/101631262-bedc1b00-3a2c-11eb-9c5c-4d7f4ad8acf0.png)

**Comment by ZetCreate** [comment]
![изображение](https://user-images.githubusercontent.com/48327170/101631917-d10a8900-3a2d-11eb-8217-b4262e3c260d.png)

**Comment by TheSpringBoy** [comment]
Hi,
You need to update your amongus to version 2020.12.5s

**Comment by ZetCreate** [comment]
Ok, thanks, i will try

**Comment by ZetCreate** [comment]
Uh, i got another error 
![изображение](https://user-images.githubusercontent.com/48327170/101633990-bbe32980-3a30-11eb-91d2-b961fd4ce308.png)

**Comment by ZetCreate** [comment]
I've got answer
