### ISSUE TITLE
Error message when trying to open CrewLink on Manjaro Linux

### ISSUE THREAD

**Issue by SashoStoichkov** [ottomated/CrewLink#281]
![image](https://user-images.githubusercontent.com/24972335/101678116-2ebac780-3a66-11eb-95b6-c12afc205996.png)

**Comment by TheSpringBoy** [comment]
Hi, at the moment the software does not support linux

**Comment by TheShadowEevee** [comment]
This is the same as #4

**Comment by SashoStoichkov** [comment]
Thank you both 👍🏻

**Comment by C0rn3j** [comment]
@SashoStoichkov Can you close this since it's a dupe?

**Comment by SashoStoichkov** [comment]
Yeah, sure. Sorry
