### ISSUE TITLE
Can't hear people who died.

### ISSUE THREAD

**Issue by zlyfer** [ottomated/CrewLink#283]
I tried this tool today and it seems pretty fine, but when some people die they can't hear each other after next round start.

**Comment by SvenvtH** [comment]
Could you be more specific. Do you mean next game or next round?

It's programmed that dead people can't communicate with alive users, but they can hear alive players.

**Comment by zlyfer** [comment]
So I tried crewlink with a few friends and following happened:
We we're 6 people ingame (& in crewlink) and started to play. 2 people died before the first meeting and as expected, we couldn't hear them but they could hear us. After the meeting another crewmate died and in the next meeting the imposter got kicked out and the round ended. After that the 2 dead players could not hear each other but heard anyone else (and got heard as well). We started a new lobby in Among Us and they both restarted their crewlink but it didn't get fixed. I had to restart the whole crewlink server to get them to hear each other again.

**Comment by devindperez** [comment]
https://github.com/ottomated/CrewLink/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by SvenvtH** [comment]
> https://github.com/ottomated/CrewLink/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

This issue was created before the release of the issue template.



> So I tried crewlink with a few friends and following happened:
> We we're 6 people ingame (& in crewlink) and started to play. 2 people died before the first meeting and as expected, we couldn't hear them but they could hear us. After the meeting another crewmate died and in the next meeting the imposter got kicked out and the round ended. After that the 2 dead players could not hear each other but heard anyone else (and got heard as well). We started a new lobby in Among Us and they both restarted their crewlink but it didn't get fixed. I had to restart the whole crewlink server to get them to hear each other again.

All the users should restart their crewlink client ( You can also do CTRL + R ). This should resolve the issue.
