### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by SvenvtH** [ottomated/CrewLink#285]
Would it be possible to create mobile support for crewlink?

**Comment by clavicz** [comment]
Can we do among us proximity on mobile

**Comment by QPixel** [comment]
It is impossible for CrewLink to work on mobile.

**Comment by Baecon** [comment]
unless he plans on making a mobile version of crewlink(and that'll only be available for android) i highly doubt it. Just buy the game its $5 and you're supporting the devs. Its also not demanding to run and im convinced a potatoe can run this game

**Comment by SvenvtH** [comment]
> unless he plans on making a mobile version of crewlink(and that'll only be available for android) i highly doubt it. Just buy the game its $5 and you're supporting the devs. Its also not demanding to run and im convinced a potatoe can run this game

I do own the game on pc, but some of my friends don't own a desktop pc or laptop. Mostly have Chromebooks which are not able to install any files from the internet without rooting/cracking Chrome OS. That's why I requested a mobile application for this.

**Comment by gr01d** [comment]
I second this, we need mobile, mac and linux support (electron).
Is there any project out there that already supports proximity chat with among us that is cross platform?

**Comment by LordDraagonLive** [comment]
Better fork this repo and build a mobile version

**Comment by MrBaggieBug** [comment]
> Would it be possible to create mobile support for crewlink?

400 more bugs to have fun with 😅

Im joking btw, this project is absolutely great
