### ISSUE TITLE
Mobile/APK Support

### ISSUE THREAD

**Issue by AKGBComrade** [ottomated/CrewLink#29]
Me as an underage user, I do not have online banking. Therefore I can not buy the PC version on Steam or Itch.io... So to be able to play Among Us I use a free mobile emulator called BlueStacks. Now of course, CrewLink doesn't work on BlueStacks, so I would very much appreciate it if you could make a mobile version of CrewLink.

-Kind Regards, KGBComrade

**Comment by ottomated** [comment]
It's not possible to do this on mobile because it would require root access and a full rewrite.
