### ISSUE TITLE
Allow subdirectory for voice server URLs

### ISSUE THREAD

**Issue by CabbageCanFly** [ottomated/CrewLink#291]
It'd be nice to utilize my existing domain/server and just append a subdirectory, specifically for https access. Not using https for now.

socket.io seems to ignore subdirectories unless you specify something like this:
[https://stackoverflow.com/questions/25896225/how-do-i-get-socket-io-running-for-a-subdirectory](https://stackoverflow.com/questions/25896225/how-do-i-get-socket-io-running-for-a-subdirectory)

Perhaps I'm missing something and this may not be necessary. I'm using nginx.

I might make a pull request if I get around to this.

**Comment by CabbageCanFly** [comment]
@ottomated Is this a trivial thing? I'm kinda new to handling a webserver and nginx and stuff, so I would appreciate some insight into why this issue was closed without a comment.

**Comment by SvenvtH** [comment]
> @ottomated Is this a trivial thing? I'm kinda new to handling a webserver and nginx and stuff, so I would appreciate some insight into why this issue was closed without a comment.

Add me on discord: RedReflex#6613 and I would be more than happy to help :)

**Comment by CabbageCanFly** [comment]
I ended up just using a subdomain. I didn't want to bother doing this earlier because I didn't have a wildcard certificate at the time.

Still would appreciate a response to why this ticket was closed.
