### ISSUE TITLE
When I Open Among Us It Still Searches For It

### ISSUE THREAD

**Issue by Happy2745** [ottomated/CrewLink#292]
When I Press Open Among Us It Sends Me To The Page Where You Would Buy Among Us Even Though I Have It Installed And I Can Still Launch It. When I Launch It, It Will Say Searching For Among Us.

**Comment by SvenvtH** [comment]
> When I Press Open Among Us It Sends Me To The Page Where You Would Buy Among Us Even Though I Have It Installed And I Can Still Launch It. When I Launch It, It Will Say Searching For Among Us.

Please don't use cracked versions of among us as this is illegal
