### ISSUE TITLE
Potential Feature: Directional Audio

### ISSUE THREAD

**Issue by Tazanno** [ottomated/CrewLink#3]
Audio panning should change to denote direction of other players. Directions include all cardinals and are additive.
Makes finding other players based on audio much easier, and generally makes sense.

**Comment by ottomated** [comment]
It does do that already, unless there's a bug that prevents it from working. Take a look at https://github.com/ottomated/CrewLink/blob/dc4ca786c44a8aacd01297f3677d17587e12a200/src/renderer/Voice.tsx#L60

**Comment by ottomated** [comment]
Closing until more info is provided.
