### ISSUE TITLE
[BUG REPORT] Version not supported

### ISSUE THREAD

**Issue by InsideBSI** [ottomated/CrewLink#302]
Hi, I'm not using the template because this issue don't need it.
New version got released, CrewLink says version not supported since the new update

**Comment by InsideBSI** [comment]
Why is that every new release every third party softwares break all at once ? Is it because how unity deploy updates or something ?

**Comment by vrnagy** [comment]
Beacuse the 3rd party softwares are reading the games memory and the adresses are changing between releases

**Comment by InsideBSI** [comment]
I may be missing something, but aren't memory addresses supposed to be dynamically allowed anyways?

**Comment by vrnagy** [comment]
Process memory addresses. The mods reading the data based on offsets from the GameAssembly.dll's position.

Yeah, an official api would be very good

**Comment by InsideBSI** [comment]
I see, there's nothing else to do exept to wait, then.
Does it really help to report new updates like I just did or are you guys aware of it anyways ?

**Comment by ottomated** [comment]
ALL ISSUES NEED THE TEMPLATE YOU FOOL

**Comment by InsideBSI** [comment]
Made it
