### ISSUE TITLE
[BUG REPORT] Version not supported

### ISSUE THREAD

**Issue by InsideBSI** [ottomated/CrewLink#303]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
CrewLink won't work because of AmongUs's new update

**To Reproduce**
Steps to reproduce the behaviour:
1. Update your game via steam
2. Try to use CrewLink

**Expected behaviour**
CrewLink will not go past the Menu phase because of new update of among us

**Screenshots**
N/A

**Desktop (please complete the following information):**
AmongUs v2020.12.9s
CrewLink V1.1.5

**Additional context**
Here is your issue with the template
duplicate of https://github.com/ottomated/CrewLink/issues/302

**Comment by sgranger2** [comment]
This is probably affecting everyone after the Among Us v2020.12.9s update

**Comment by InsideBSI** [comment]
It is indeed affecting everyone since the new update. see https://github.com/ottomated/CrewLink/issues/302 if you want to know why

**Comment by varedz** [comment]
He'll be grabbing them from AutoMuteUs soon lmao

**Comment by InsideBSI** [comment]
So you're telling me automuteus is already patched ?

**Comment by varedz** [comment]
Yeah I update the pointers within 2 minutes when I'm told

**Comment by varedz** [comment]
https://github.com/denverquane/amonguscapture/blob/master/Offsets.json

**Comment by ottomated** [comment]
*yoink*

**Comment by InsideBSI** [comment]
Yeah, just saw that, nice job

**Comment by varedz** [comment]
LOL

**Comment by griffleberrypie** [comment]
Sorry, I'm not a coder or programmer.  I've seen this thread is closed as well as another #304 duplicate thread.
This still seems to be an issue as it's still bugging for me.  I'm not sure if I should create a new thread or if that will just get closed for being a dup as well.

Though it is working for my desktop, for some reason it's not working for my laptop, if that adds anything.

**Comment by giggleButt** [comment]
> I've seen this thread is closed as well as another #304 duplicate thread.
> This still seems to be an issue as it's still bugging for me. I'm not sure if I should create a new thread or if that will just get closed for being a dup as well.

Yeah, my friend was also continuing to have this same issue after the report was closed. 
> Though it is working for my desktop, for some reason it's not working for my laptop, if that adds anything.

It seems to be working on one of my laptops, but not both. Big ol' shrug.
