### ISSUE TITLE
[BUG REPORT] Among Us update bug - Current version not supported

### ISSUE THREAD

**Issue by JKanczura** [ottomated/CrewLink#304]
**Describe the bug**
Among Us released a patch on 12-10-2020, making CrewLink respond with an unsupported version error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open CrewLink while in a lobby
**Expected behaviour**
CrewLink to connect to the lobby 

**Screenshots**
![image](https://user-images.githubusercontent.com/16521437/101847907-49527680-3b22-11eb-8198-f25bb832a1ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.5

**Comment by ottomated** [comment]
Duplicate.
