### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by h805** [ottomated/CrewLink#310]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X ] I am using the Steam version of Among Us
3. [X ] I have tried to use an [alternative voice server server](https://status.crewl.ink/)
4. [X ] I have checked everyone in my lobby is on the same CrewLink server
5. [X ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X ] I have checked that the CrewLink server I'm using is up to date
7. [X ] I have a screenshot of any errors
8. [X ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
After latest release, no one is able to talk to each other. We have re-installed, rebooted and rebooted our application and machines.

**Desktop (please complete the following information):**
 - OS: All Windows 10
 - Version: 1.1.6

**Comment by ottomated** [comment]
Needs reproduction instructions
