### ISSUE TITLE
[BUG REPORT] SOLID GRAY WINDOW UPON INSTALLATION, NO MENU OR BUTTONS

### ISSUE THREAD

**Issue by sevthefailure** [ottomated/CrewLink#311]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

When I installed Crewlink, it completed installation, and the window is just solid gray. No buttons, or anything. I opened Among Us, joined a lobby, trying to see if it would change: nothing.

Also, cannot move the window at all, it's just stuck in the middle of my screen. I can have it in front of or behind other windows, but that's all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Crewlink

**Expected behaviour**

I expected to see a menu or something.

**Screenshots**

![image](https://user-images.githubusercontent.com/75822487/101859044-87569700-3b30-11eb-8d41-bf12b149404a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

**Comment by sgranger2** [comment]
This Issue will probably be closed as a duplicate but please try the temporary solution at #305 and see if that works for you

**Comment by sevthefailure** [comment]
Nvm, issue's been fixed with the new 1.1.6 update. Closing this now.

**Comment by Bathroom420** [comment]
Hey im still having this issue on 1.16. Any luck?

**Comment by sgranger2** [comment]
> Hey im still having this issue on 1.16. Any luck?

Make sure you re-download the exe from releases and try again. If you still have the issue try to run the program in Command Prompt by doing `cd Desktop` and then `CrewLink.lnk`
