### ISSUE TITLE
[BUG REPORT] Among Us Version 2020.12.9 still unsupported on 1.16

### ISSUE THREAD

**Issue by warlordkingdom** [ottomated/CrewLink#312]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Despite updating to 1.16, my Among Us is still unsupported for some reason.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download CrewLink-Setup-1.1.6.exe
2. Run CrewLink-Setup-1.1.6.exe
3. Pop up for unsupported version
**Expected behaviour**
1.16 should support version 12.9

**Screenshots**
![2020 12 10-22 49_01](https://user-images.githubusercontent.com/64113893/101859626-174d0e80-3b3a-11eb-83cb-521dd74a7920.png)
![2020 12 10-22 49](https://user-images.githubusercontent.com/64113893/101859632-19af6880-3b3a-11eb-9f31-b59a43334838.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version: 1.16

**Comment by warlordkingdom** [comment]
I have tried uninstalling and reinstalling multiple times as well.

**Comment by wanderingcoconut** [comment]
I'm getting the same problem and have uninstalled and reinstalled as well.

**Comment by sevthefailure** [comment]
I'm not even getting a menu. It's just solid gray for me lmao

**Comment by warlordkingdom** [comment]
> I'm not even getting a menu. It's just solid gray for me lmao

Yep, that happened to everyone in my friend group but me.

**Comment by Skkkitzo** [comment]
I was having a problem of my own about an hour ago, and I reinstalled it and got the exact same problem. Ottomated is currently trying his hardest to fix the problems, you can see from his commits, and he may make a few more bugs along the way. My suggestion is to follow what I did in #305 as a temporary solution.

**Comment by wanderingcoconut** [comment]
> I have tried uninstalling and reinstalling multiple times as well.
If you switch voice servers, it should work. :)

**Comment by warlordkingdom** [comment]
> > I have tried uninstalling and reinstalling multiple times as well.
> > If you switch voice servers, it should work. :)
> > Use this link to find a voice server: https://status.crewl.ink/

The temporary solution in #305 worked for me! :)

**Comment by sgranger2** [comment]
v1.1.6 was just updated not long ago, please try again. My friends that were getting the grey box are now playing with proximity chat just fine with the latest 1.1.6 download

**Comment by ottomated** [comment]
You have clearly not tried an alternate voice server. Your server is out of date.
