### ISSUE TITLE
Weird Glitch

### ISSUE THREAD

**Issue by E10Panda** [ottomated/CrewLink#313]
Whenever i try to launch CrewLink it comes up with an error telling me to restart CrewLink, so I do. The error keeps popping up and I haven't been able to use CrewLink at all. (Ive tried reinstalling) Also, I got an alert saying it needed webcam access?

**Comment by DaBomber60** [comment]
Can you send us a screenshot (windows key + shift + S) so we can see the error?

**Comment by Skkkitzo** [comment]
It would also help us greatly if you can use the proper format, which can be found [here](https://github.com/ottomated/CrewLink/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG+REPORT%5D)

**Comment by TheSpringBoy** [comment]
> Whenever i try to launch CrewLink it comes up with an error telling me to restart CrewLink, so I do. The error keeps popping up and I haven't been able to use CrewLink at all. (Ive tried reinstalling) Also, I got an alert saying it needed webcam access?

I guess that you need to swap your voice server.
but you will need to add screenshot...

any way. you can use this server:
https://eu-crewlink.herokuapp.com/

**Comment by Skkkitzo** [comment]
Or alternatively use the popular US-based http://crewlink.glitch.me/

**Comment by ottomated** [comment]
Template
