### ISSUE TITLE
[BUG REPORT] Voice is either not detected, or does not turn off.

### ISSUE THREAD

**Issue by Skkkitzo** [ottomated/CrewLink#315]
**Describe the bug**
When using default microphone, no input audio is detected. Switching to the microphone from the drop down menu in settings, the microphone is CONSTANTLY detected, even when no sounds are made. Switching back to the default setting changes nothing. Only way to fix is to reinstall crewlink entirely.

**To Reproduce**
The glitch can only start when joining a new lobby, but will persist into the next one if you leave.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**
Green cirlce is either on or off the entire time.

**Comment by ottomated** [comment]
More info needed. What sound is transmitted to people in game

**Comment by Skkkitzo** [comment]
> 
> 
> More info needed. What sound is transmitted to people in game

Not really sure what else you want on this. The mic is either constantly on, or it wont pick up anything. That's it.
