### ISSUE TITLE
[BUG REPORT] config.json cannot be manually adjusted (even with CrewLink closed)

### ISSUE THREAD

**Issue by JerryPLayz** [ottomated/CrewLink#320]
**Goal** (for clarity, It'll make more sense)
I am attempting to find a way to "automatically" configure Crewlink after an update.
That would require:
**Steps for Reproducing**
1. Removing all files from the previous installation (Able to do fine, but you really should have an uninstaller / updater packaged with it)
2. Downloading (if needed)  the updated 'setup.exe' and executing it  (Works fine)

3. Configuring the "Config.json" in AppData/Roaming/crewlink with previous settings. (This works, but then causes the bug of which I am reporting)

**Describe the bug**
Upon adjusting the Config.json (in any way that is syntactically correct) causes all elements (except the background element) to not show up. I am using JSON.NET (C#) in an application I am developing to assist in various things regarding CrewLink.

Also, another issue I found while testing is that of the JSON object being appended to after creation (in the form of offset data) - not sure whether this is intentional for any reason, but in general, is not a good idea.

**Expected behaviour**
In general, for any syntactically correct JSON object, the config.json file should be readable by the program.
This is a mix between a Bug Report and a Feature Request in the eventuality that its a logical error.

**Desktop (please complete the following information):**
 - OS: Windows 10

Example Input (from my program into config.json):
`
{"alwaysOnTop":false,"microphone":"6b21a69137df18d9f277670a761314f28a7c038330cc47d800594d09543c43a2","speaker":"fced1b6890543ece481ebbd2a70e342da46a5f87d1cac7250c9b1348e7edde26","pushToTalk":false,"serverURL":"http://MY_IP:9736/","pushToTalkShortcut":"V","deafenShortcut":"RControl","hideCode":"false","enableSpatialAudio":true,"__internal__":{"migrations":{"version":"1.1.6"}}}
`
Result from re-opening CrewLink:
![image](https://user-images.githubusercontent.com/26833036/101911795-d5849c80-3bfb-11eb-9f83-edf2da45df9e.png)

To confirm the JSON is syntactically correct, I have put it into JSON Editor Online:
![image](https://user-images.githubusercontent.com/26833036/101912178-5c397980-3bfc-11eb-8f64-13f91fc5c343.png)

Regards,
Jerry

**Comment by sjoerd108** [comment]
Crewlink not just checks for validity of JSON syntax itself but will also check for value types and formatting of some strings. If it deems the JSON to not match what it expects (e.g. the serverURL is not a properly formatted URL) then it throws an error and refuses to start. (Check the console to see what the validator deems to be wrong with the file)

The offsets you see appear are intentional. Upon starting, CrewLink fetches the latest memory offsets for the version of Among Us in use and caches them in this file. 

Despite it's name, the file is there to persist application state more than anything else and isn't very user friendly. As such, there's no fallback code to deal with malformed config files and it crashes if you change it in any way that it can't handle.

**Comment by JerryPLayz** [comment]
So, what kind of validation does it do? I had a look at the Source code for a bit and found where it queried the config file. I checked where you define lSettings.ts and followed those variable types - so that shouldn't be a problem. So, what's wrong with my input example that could cause it to error? (As I said, I'm writing this software externally; as Im not developing a feature for CrewLink.

**Comment by sjoerd108** [comment]
If you check Settings.tsx, specifically at [this line](https://github.com/ottomated/CrewLink/blob/84a5979e2034cd9cbb0c0c9a3756c40892d9314b/src/renderer/Settings.tsx#L51), you can see how the JSON schema is defined. This is pretty much what it expects from config.json. As for what is wrong with your version, "hideCode" is set to a string containing "true", this should be a boolean instead. You can check the console yourself by pressing CTRL + SHIFT + I.

**Comment by JerryPLayz** [comment]
I wasn't looking at the .tsx files..... probably should be... After some looking it was wrong variable type... Thanks for your help!
