### ISSUE TITLE
[BUG REPORT] Please use another voice server.

### ISSUE THREAD

**Issue by dzape** [ottomated/CrewLink#322]
What should i type in the voice server or should i host my own ?

Everything i type is red and I cant save it.

![image](https://user-images.githubusercontent.com/47067384/101923078-3ea1eb00-3bcf-11eb-9af2-a465b25a8bae.png)

![image](https://user-images.githubusercontent.com/47067384/101923349-92accf80-3bcf-11eb-9641-391b3718e34f.png)

**Comment by TomahawkMango** [comment]
Im having the same problem and anything a try says the same error

**Comment by MortBlox** [comment]
me too, the server isnt online

**Comment by nutellabrain** [comment]
same problem

**Comment by andrewyuan02** [comment]
Same problem

**Comment by dzape** [comment]
Try putting http://54.192.94.35:9736 this worked for me but the servers are full all the time. 

![image](https://user-images.githubusercontent.com/47067384/102686329-3822fd00-41e7-11eb-83a2-a4a2119a0e9f.png)
