### ISSUE TITLE
[BUG REPORT] Current Steam version is v2020.12.9s 

### ISSUE THREAD

**Issue by Micky207** [ottomated/CrewLink#323]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [Y ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [Y ] I am using the Steam version of Among Us
3. [Y ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [Y ] I have checked everyone in my lobby is on the same CrewLink server
5. [Y ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [Y ] I have checked that the CrewLink server I'm using is up to date
7. [Y ] I have a screenshot of any errors
8. [Y ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Current Steam version is v2020.12.9s but CrewLink prompts to use v2020.12.5s
There is no option to rollback the game version on Steam.

**Comment by soymingu** [comment]
i have changed the server to https://crewlink.among-us.tech/ and now is working
