### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Nin10doYT** [ottomated/CrewLink#325]
![image](https://user-images.githubusercontent.com/69506597/101940949-38b40600-3bdf-11eb-84d1-ab34a303f7f8.png)
i cant seem to get it to work for some reason, help appreciated.

**Comment by KylevanRaaij** [comment]
use another voice server. You can make your own or find one here : https://status.crewl.ink/. Go to settings and past one of the URL's in the voice server thingy
