### ISSUE TITLE
[BUG REPORT] Can still hear and talk while deafened at the end of the round

### ISSUE THREAD

**Issue by Dvckfield** [ottomated/CrewLink#326]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
While deafened (clicking Rctrl) you can actually hear and talk with everyone at the defeat/victory screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '..'

**Expected behaviour**
I expected it to stay deafened

**Screenshots**
Cannot because its a voice problem

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

**Comment by ottomated** [comment]
You have obviously not followed the checklist because otherwise this would be fixed.
