### ISSUE TITLE
BUG REPORT: Black Screen

### ISSUE THREAD

**Issue by Bathroom420** [ottomated/CrewLink#329]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

Whenever we go to open Crewlink, it just shows a black screen.
**To Reproduce**
Black Screen, no Error indicated 
**Expected behavior**

**Screenshots**

I do have 1 screenshot
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

**Comment by ottomated** [comment]
Redownload 1.1.6
