### ISSUE TITLE
[BUG REPORT] Status Code 521 

### ISSUE THREAD

**Issue by BenjurBenjur** [ottomated/CrewLink#331]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
 When I try to launch crewlink its gives me this error telling me to use another voice server and gives me error 521. Anybody know how to fix this? 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

Thanks for your time!

**Comment by RunKittenzRComing** [comment]
Same issue. Friend has it too.

**Comment by BenjurBenjur** [comment]
Join the discord then go to crewlink servers and they have active servers that are up that you can put in place of the one you have now and it will fix it

**Comment by BenjurBenjur** [comment]
> Same issue. Friend has it too.

**Comment by SanfordP** [comment]
> Join the discord then go to crewlink servers and they have active servers that are up that you can put in place of the one you have now and it will fix it

Which discord specifically?

**Comment by BenjurBenjur** [comment]
> > Join the discord then go to crewlink servers and they have active servers that are up that you can put in place of the one you have now and it will fix it
> 
> Which discord specifically?

https://discord.gg/cJraqzy3

**Comment by ottomated** [comment]
Use a different voice server

**Comment by cycycon** [comment]
discord link expired
