### ISSUE TITLE
[BUG REPORT]  Can't hear some peoples

### ISSUE THREAD

**Issue by SevenX159** [ottomated/CrewLink#334]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ Yes ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ Yes ] I am using the Steam version of Among Us
3. [ Yes; even Private hosted one ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ Yes ] I have checked everyone in my lobby is on the same CrewLink server
5. [ Yes ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ Yes ] I have checked that the CrewLink server I'm using is up to date
7. [ No ] I have a screenshot of any errors
8. [ Yes ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

I just setup a private voice server ( Because public one had the issue )
But we still have the issue where some peoplee can't hear some other people ( not everyone )
i have to change mic and speaker to something else and back to default to make it rework again ( Seems like a refresh on the APP ) CTRL+R do the same but i still have some people i can't hear ( It just change the people i can't hear )
I'm not the only one having that issue, and we tried on differents server which do the same on all of them

The circle arround the people doesn't show up in green when they speak, but when i refresh it i works

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a game with Crewlink
2. Check if you hear everyone
3. Finish the game
4. Restart a new one without remaking the lobby
5. Recheck if you hear everyone
           For me, it change each new game wich people i can hear ( arround half the people each times)

**Expected behaviour**

Hear everyone on each games

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: [1.1.6]
 - Server Version ; Fast build zith docker command
                            Tried in public server too 

**Additional context**

**Comment by ottomated** [comment]
Didn't do the checklist
