### ISSUE TITLE
Can hear all players some times

### ISSUE THREAD

**Issue by Obsolution** [ottomated/CrewLink#336]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x ] I am using the Steam version of Among Us
3. [x ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

So this only happened about 2-3 times in a span of two hours, but what initially happens is that when we get into the match nearing around 5-6 players everyone can hear one another as if they're next to each other when they actually aren't.

**To Reproduce**
Steps to reproduce the behaviour:
Not sure how this happens

**Expected behaviour**

I expected to not hear anyone unless they are in my radius

**Screenshots**
Unfortunately I don't have any screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

**Comment by ottomated** [comment]
ctrl-R, duplicate

**Comment by asinn** [comment]
> ctrl-R, duplicate

Sorry chief. That ain't it. I'm having the same issue with 1.1.6 and CTRL+R multiple times with all players isn't working. You have a bug.
