### ISSUE TITLE
[BUG REPORT] OPENSSL WRONG_VERSION_NUMBER error

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ottomated/CrewLink#338]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ Y] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ Y] I am using the Steam version of Among Us
3. [ Y] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ Y] I have checked everyone in my lobby is on the same CrewLink server
5. [ Y] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ Y] I have checked that the CrewLink server I'm using is up to date
7. [ Y] I have a screenshot of any errors
8. [ Y
![CrewLinkError](https://user-images.githubusercontent.com/11295899/101969127-c1876d80-3bf0-11eb-8a4c-e8c7dfd83782.png)
] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

When I try to connect to my friend's CrewLink server, it throws the error in the attached screenshot. My other friends can connect to it, and it happens before I even launch Among Us. The server owner reports that he doesn't see anything in his console, but when I run Wireshark, I can see packets go back and forth between us. I've reinstalled crewlink and it still has the same problem.
**To Reproduce**
Steps to reproduce the behaviour:
I set the voice server to my friend's IP address https://octet.octet.octet.octet/ and it throws an error as soon as I close the setting pane.
**Expected behaviour**

I expected it to connect to the server and idle while I open Among Us
**Screenshots**

I attached one
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]
OS: Windows 10 Pro version 1909 OS build 18363.1139

**Additional context**

**Comment by ottomated** [comment]
use http instead of https
