### ISSUE TITLE
[BUG REPORT] Norton detects that CrewLink is trying to use the computer's webcam!

### ISSUE THREAD

**Issue by Verdagon** [ottomated/CrewLink#339]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Norton detects that CrewLink is trying to use the webcam, see screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run crewlink for the first time.

**Expected behaviour**
No Norton popup.

**Screenshots**
https://i.imgur.com/m25ZIuo.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Yes

**Additional context**

**Comment by Shadow-WolfDemon** [comment]
This might be because its using the microphone

**Comment by ottomated** [comment]
navigator.getUserMedia must be detected by Norton. This is on their end, no possible fix.

**Comment by OiYouYeahYou** [comment]
Well that's interesting! Are you using a webcam for your mic?

CrewLink is using an API that is one change to enabling webcam, but is currently hard disabled. Though this might be unavoidable given CrewLink is using a web API

https://github.com/ottomated/CrewLink/blob/c7151d0b7680e9149c41ff6fa6db0575e79e83be/src/renderer/Voice.tsx#L178
