### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Garvington** [ottomated/CrewLink#341]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [yes ] I am using the Steam version of Among Us
3. [ yes] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [no ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [yes ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
My friends and I have been trying to do among us proximity chat on stream and half of us can get the app to work just fine no problem but the rest of us get and error code 521 or it says we are on the wrong version but everyone is one the same one non beta and the half of our group cannot play the game. is there a reason for this? 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

**Comment by ottomated** [comment]
Use the same voice server. Try alternates.
