### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by costeirinha123** [ottomated/CrewLink#347]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [ ] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**
It only allows 64-bits computers to play, so in that matters i can't play, wich is unfortune because it looks really cool, would you be able to resolve that issue?

**Comment by OiYouYeahYou** [comment]
Duplicate and is being worked on here #263

**Comment by costeirinha123** [comment]
I dont know how to do that..

Ricardo Sousa


ottomated <notifications@github.com> escreveu no dia sábado, 12/12/2020
à(s) 19:36:
