### ISSUE TITLE
[BUG REPORT] App not loading/starting

### ISSUE THREAD

**Issue by MrMastaofDesasta** [ottomated/CrewLink#349]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

The Crewlink App does not even start. All that appears is a nonresponsive grey rectangle floating on my screen. It appears as the crewlink client in the Windows Taskbar and can be closed from there, but otherwise nothing can be done with it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Crewlink
2. Crewlink does not start

**Expected behaviour**

I expected Crewlink to start up like in the Tutorial video and that I would be able to operate it as shown, e.g. change voiceserver, start game, etc...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

I downloaded the app from Softpedia, as the download speed with Github was abyssmal (~5kb/s)

**Comment by ottomated** [comment]
I can't help if you downloaded an unofficial version.

**Comment by MrMastaofDesasta** [comment]
> 
> 
> I can't help if you downloaded an unofficial version.

I downloaded the version from Github now, and it does work now. The Softpedia page seems pretty official though, maybe you have an impostor there...
