### ISSUE TITLE
CrewLink not connecting

### ISSUE THREAD

**Issue by Blade324** [ottomated/CrewLink#35]
I downloaded crew link and everything is fine until I click open game and among us opens but crew Link is still saying waiting for among us and open game. I've tried redownloading it and it still says waiting for among us and open game even when I open it through crew Link. I'm not play on the beta.

**Comment by heygleeson** [comment]
Among Us has updated, which has affected the offsets CrewLink uses to get game data, causing all kinds of [issues](https://github.com/ottomated/CrewLink/issues/19).
Try deleting the folder (`C:\Users\xxx\AppData\Roaming\crewlink\`)

**Comment by Blade324** [comment]
I've tried looking up the folder and It says I don't have it all I have is the CrewLink-Setup-1.1.2.exe

**Comment by fancythedeveloper** [comment]
Try typing `%appdata%` in the run box and going to the crewlink folder.
