### ISSUE TITLE
Can´t change Server

### ISSUE THREAD

**Issue by DanceStar** [ottomated/CrewLink#350]
I can´t change the Server. I tiped in the wrong IP and when i want to change it, it doesn´t keep it saved. It´s always using the old IP.

**Comment by Nerdman1681** [comment]
Yeah I had the same issue. I even tried deleting the data but it won't save and some times it won't even let mem enter a new IP

**Comment by Nerdman1681** [comment]
Won't even work on an older version (Even after I tried deleting the files and using 1.15)

**Comment by ottomated** [comment]
Template.
