### ISSUE TITLE
[BUG REPORT] You are on an unsupported version of Among Us: 2020.12.9. Correct voice servers used.

### ISSUE THREAD

**Issue by Goose8934** [ottomated/CrewLink#354]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [n/a] I have checked everyone in my lobby is on the same CrewLink server
5. [n/a] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [X] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
'crewlink' dialog box: "You are on an unsupported version of Among Us: 2020.12.9.  Restart the app after you fix this."

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'CrewLink'
2. See error

**Expected behaviour**
For CrewLink to fully launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/75919363/102001412-d67e1100-3d56-11eb-98de-cebe7d8ff3b3.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Version: 10.0

**Additional context**
Please note that **I have tried both of the alternative voice servers** (as per https://github.com/ottomated/CrewLink/issues/250), uninstalled/reinstalled CrewLink, and tried launching CrewLink before and after launching Among Us in Steam.

**Comment by oraki23** [comment]
Updating / Pulling the new server version from Docker or other source has worked for me.
If you don't own the server, you might have to wait.

**Comment by beavelar** [comment]
Verify up to date voice server version is deployed, had this issue appear with a older voice server version and fixed when updated.

As such this bug should probably be written in https://github.com/ottomated/CrewLink-server

**Comment by spacejamjim** [comment]
So there was someone with this issue in the help channel of the discord. I let them use my heroku link due to the solution posted here https://github.com/ottomated/CrewLink/issues/282 about the server being full... and they said they no longer received the error. If it's not a huge PR, perhaps an error message reflecting the potential for this would assist users in solving it themselves

**Comment by Tothas** [comment]
You have to enable auto deployment from github on the Deploy tab of Heroku. Click Github under Deployment Method and then connect it to your fork in the next section below.

But that will only keep it updated from your fork, or copy, of the crewlink-server. To keep that auto updated with the latest release of otto's main fork, I suggest using https://github.com/wei/pull

**Comment by Goose8934** [comment]
Thanks all. I believe this has fixed itself - I did not do anything differently:

![image](https://user-images.githubusercontent.com/75919363/102007259-5f636f80-3d8c-11eb-9e04-5a21c67aae03.png)

**Comment by spacejamjim** [comment]
@Goose8934 the issue fixing itself could likely have been the server becoming less populated. If others see this, please don't think the issue will solve itself like this.
