### ISSUE TITLE
[FEATURE] Add an Auto-Updater so we dont have to manually install every time.

### ISSUE THREAD

**Issue by n1azx** [ottomated/CrewLink#359]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [x] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheSpringBoy** [comment]
Hi, this is a feature that already exists in the software

**Comment by Skkkitzo** [comment]
> 
> 
> Hi, this is a feature that already exists in the software

It doesn't always work perfectly though.
