### ISSUE TITLE
[BUG REPORT] Settings not saving on reload/shut down

### ISSUE THREAD

**Issue by Nerdman1681** [ottomated/CrewLink#367]
**Describe the bug**
I went to type in my voice server as I just got it up recently it won't let me type in the text box. Tho I found a fix for that ctrl + alt + tabbing in and out fixes it. Though once I put it in it dosn't save it shows the IP I put in but when I restart the app it gives me the error Please use another voice server "server https://" For some reason when I deleted the default server it saved https:// and will not let me save another IP. I've tried uninstalling, deleting the data from APPDATA and using ctrl + R.
1. I open settings,
2. I ctrl + alt + tab in and out of the app so it will let me enter text in the text box for the voice server IP
3. I type in my IP
4. I close (or ctrl + R) the app and it stills gives me the error message that "https" is not a valid server. Even tho I typed in my server IP. 

**Expected behavior**
It should save me server IP

**Desktop (please complete the following information):**
 - OS: Windows 10 pro

**Additional context**
I'm using the latest version of Crew Link

**Comment by stevebell117** [comment]
Can you confirm that there is no space at the beginning of the ServerURL? Sometimes when I type/paste the link over there it appends a space at the start and it's not obvious.

**Comment by baconpie** [comment]
same here

**Comment by Nerdman1681** [comment]
I'm not copy/pasting so yes I can confirm that there is no space at the begging of the URL.  Tho that's not the problem it's just what I type in isn't saving at all. It's still stuck on the https:// of the default Ip where I deleted it to put in mine.

**Comment by coolmaus** [comment]
I'm having the same problem right now and I don't know have to fix it.

**Comment by Nerdman1681** [comment]
Ok well I got it to save I tried to put in the IP just straight up (Example: 0.0.0.0:port) I then tried LocalHost:PORT but that didn't work.  Finally, I did http://[ip]:[port] and it gave me a different error code. I assume this means that it at least found a server. So yeah when putting in your IP make sure to add http:// or https://
