### ISSUE TITLE
[BUG REPORT] lobby kicking and audio issues

### ISSUE THREAD

**Issue by Mystique98** [ottomated/CrewLink#373]
Crewlink V1.1.96 beta  , windows 10

**Describe the bug**
flagged as a hack more often or kicked from lobby while using crew link , Voice chat experiences audio issues such as robotic feedback even while not using discord and deafened 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.196

**Comment by Ornamus** [comment]
There is no "CrewLink 1.1.96 Beta" - CrewLink has no official betas, and the latest version of the app is 1.1.6.

**Comment by Mystique98** [comment]
The program  was called beta hence why I said beta

**Comment by ottomated** [comment]
This is an unsupported version.
