### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by skylatian** [ottomated/CrewLink#378]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Audio is robotic and glitchy, stutters and there's static in the background 

**To Reproduce**
Just happens, I connect to a game (all on the same server) and audio is just awful

**Expected behaviour**
Good audio

**Screenshots**
none, no errors

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [e.g. 1.1.6]

**Additional context**
n/a

**Comment by ottomated** [comment]
Probably cpu

**Comment by skylatian** [comment]
I don't think that was the issue. I have a 3600x and among us doesn't take up much cpu power, it was at very low usage. It randomly fixed itself after 30 minutes so that's good I guess.
