### ISSUE TITLE
Trojan detected on 1.1.2 installer

### ISSUE THREAD

**Issue by tnrnz** [ottomated/CrewLink#38]
Hi, I wasn't able to successfully install the application until I disabled my anti-virus software.

The anti-virus software detected a UDS:DangerousObject.Multi.Generic on the installer. But when I scanned the program directory, no viruses were found anymore. It could be only on the installer that triggered my anti-virus, perhaps a false-positive.

**Comment by ottomated** [comment]
False positive due to do hook or memoryjs. No way to fix.
