### ISSUE TITLE
[BUG REPORT] CrewLink UI flashes and is corrupted when using the PC Game Pass version of Among Us

### ISSUE THREAD

**Issue by IcedEagle** [ottomated/CrewLink#406]
**Describe the bug**
When using the PC Game Pass version of Among Us, CrewLink starts flashing random crew mate icons and corrupted text all over the UI constantly. This is unique to the Game Pass version of the game, as Steam works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and launch "Among Us" from the Xbox PC Game Pass app
2. Launch Crew Link
3. Host a private game to get into a lobby
4. Observe Crew Link UI flashing random crewmate icons and corrupted text over its UI

**Expected behaviour**
Crew Link functions with the PC Game Pass version of Among Us

**Screenshots**
(it flickers between all sorts of text and images that look like this every few milliseconds)
![image](https://user-images.githubusercontent.com/934801/102429469-6a561400-3fc7-11eb-9fcc-135d910ec54b.png)
![image](https://user-images.githubusercontent.com/934801/102429924-88bc0f80-3fc7-11eb-8d66-77f2b024c3fe.png)
For the ghost image, note that I'm in a private lobby by myself, as a cyan character with a christmas tree hat on.

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2, build 19042)
 - Crew Link Version: 1.1.6
 - Among Us Version: v2020.12.5

**Additional context**
Does not reproduce with the Steam build of the game.

**Comment by Unkn0wnNode** [comment]
Just to add onto this. Since I never installed the steam version of Among Us and only the PC Game Pass version I have an error where it's unable to find the unity analytics file.

**Comment by byzocker** [comment]
> Just to add onto this. Since I never installed the steam version of Among Us and only the PC Game Pass version I have an error where it's unable to find the unity analytics file.

https://user-images.githubusercontent.com/59401089/102553992-21d05080-40c4-11eb-9fa5-ad35bb149373.png that error message?

**Comment by Unkn0wnNode** [comment]
That is the one.

**Comment by cspotcode** [comment]
Duplicate of #411

**Comment by IcedEagle** [comment]
Closing to dupe of #411
