### ISSUE TITLE
[BUG REPORT] You are on an unsupported version of Among Us:2020.12.9

### ISSUE THREAD

**Issue by Benchaminn** [ottomated/CrewLink#409]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Hello, my friends and I have been unable to launch Crewlink for several days. Each time the same error message appears, I have already tried everything (go to beta and come back, reinstall crewlink, reinstall among us, ...) nothing changes do you know what this bug is due to? knowing that my 8 friends and I have the same problem and there is no solution on the internet (I see several people who also have this problem) Thank you for your help!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

**Comment by pietervanhoorn** [comment]
I had the same problem deleting the image in docker for the server and rebuilding it solved the issue

**Comment by Benchaminn** [comment]
oh thank you !
