### ISSUE TITLE
[BUG REPORT] Cant use app with Xbox Game Pass for PC version

### ISSUE THREAD

**Issue by byzocker** [ottomated/CrewLink#411]
#
1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [X] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar]   (https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
**i saw someone post this as a comment, but not as a direct issue**

**Describe the bug**
It can not determine the Among Us version, because the Unity Analytics File doesn't exist.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Xbox App on Windows 10'
2. Click on 'GamePass'
3. Scroll down to 'Among US'
4. Then Click on 'Play Among US'

**Expected behaviour**
You Start CrewLink, it gives you this error, you go on ok, then Relaunch App, repeat

**Screenshots**
![image](https://user-images.githubusercontent.com/59401089/102553992-21d05080-40c4-11eb-9fa5-ad35bb149373.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [Version 2004 Build 19041.685]

**Additional context**
I just installed both things played a couple rounds with the Game Pass version and then tried to start the app, this error appeard

**Comment by Caiobsama** [comment]
I also cannot use it in the Game Pass version, but this is my problem: 
![image](https://user-images.githubusercontent.com/68931886/102557558-415a7f80-40aa-11eb-8f13-34681042d7a3.png)

**Comment by KadenBiel** [comment]
From what I've seen I believe this version of Crewlink can only be used with the Steam version of Among Us. Crewlink is unable to detect the Game Pass version because it is specifically looking at the Steam directories. Hope this clears some things up.

**Comment by cspotcode** [comment]
I am a software engineer by trade and using Among Us on XBox GamePass.  If there's anything I can do to help, perhaps by sending a pull request, let me know.

**Comment by cspotcode** [comment]
I've started working on this.  I'm going to post what I'm doing here.  @ottomated if you would prefer I not spam updates here, I'll open a PR and consolidate progress updates into the description.

So far I'm using PowerShell to discover the installation location.  I'm not sure the install path is the same on all systems.

```
powershell.exe -nologo -executionpolicy remotesigned -noprofile -command "(Get-AppxPackage -name InnerSloth.AmongUs).InstallLocation"
```

**Comment by byzocker** [comment]
Thank you for the Unofficial beta version, i will check it out later today, since its 2am

**Comment by byzocker** [comment]
I think i can close this now
