### ISSUE TITLE
[BUG REPORT] Grey Box is not updated?

### ISSUE THREAD

**Issue by JesusPwnsYa** [ottomated/CrewLink#416]
1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
I downloaded Crewlink for the first time, installed it (1.1.6) and am greeted by a grey box. Just like issue #308 .

I deinstalled CrewLink, installed again and still have the same problem.

**Expected behaviour**
Get the normal screen like I've seen on screenshots and videos.

**Screenshots**
![image](https://user-images.githubusercontent.com/76225719/102650333-0a986e00-416b-11eb-8567-a640be6abcb4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version: 1.1.6

**Additional context**
-

**Comment by realwakils** [comment]
If you haven't already, try rebooting your entire computer.

**Comment by JesusPwnsYa** [comment]
Yeah I did and I did it again just now. Still a grey box.

**Comment by ChristopherPS96** [comment]
I have the same issue. Any Idea how to fix it?

**Comment by WilstonOreo** [comment]
I have the same issue. Any Idea how to fix it?

**Comment by ChristopherPS96** [comment]
I found a strange fix, redownloading the installer from github worked for me. I dont know why, since both should be the same.

**Comment by JesusPwnsYa** [comment]
Oof... yes that fixed it. Didn't think that it would be this. -.-
Thx ChristopherPS96.

**Comment by LostnFound1212** [comment]
I've had multiple versions that the greybox comes in and out. About 70% of my playtime on prox has a greybox.
It's still here for me through v1.1.6 to v2.1.8 so far.
