### ISSUE TITLE
CrewLink wont Work

### ISSUE THREAD

**Issue by Ryanneetrte** [ottomated/CrewLink#43]
I have the newest among us version and the newest crew link but it does change to menu when I open among us but once I get into a lobby it doesnt show my character and just stays on menu 

https://gyazo.com/cfe014cde8890dc743ef29694a007a5e

**Comment by nofriends69** [comment]
other people are having the same problem, there are a few solutions here you could try
https://github.com/ottomated/CrewLink/issues/28

**Comment by Ryanneetrte** [comment]
None of them work

**Comment by nofriends69** [comment]
do you have the game on steam

**Comment by Ryanneetrte** [comment]
Yes

**Comment by ottomated** [comment]
Needs more info, will reopen once provided

**Comment by Ryanneetrte** [comment]
What more info do you need?
