### ISSUE TITLE
couldn't determine the among us version unity analysis file doesn't exist

### ISSUE THREAD

**Issue by fire2O** [ottomated/CrewLink#434]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I have checked that the CrewLink server I'm using is up to date
2. [x] I have a screenshot of any errors
3. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
when i try to open crewlink this error comes up then when i press ok and relaunch crewlink the same proplem
i bought the game from the epicgames store could thet be the problem
-among us version 2020.12.9
-crew link -version 1.1.6

**Screenshots**

![1](https://user-images.githubusercontent.com/76417961/102739710-8acef700-4356-11eb-8c99-c53264c9eb32.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Comment by camilogan001** [comment]
Happening for me too, and I downloaded windows. Not sure why

**Comment by wolfymaster** [comment]
I would check your Among Us Version - it is probably not up-to-date with the Crewlink version you are using. 

see: https://github.com/ottomated/CrewLink/blob/ddcd9ca4fc025d44206561eb8f63659aa2b3facc/src/main/hook.ts#L34

It is checking the values file to get the Among Us version, but it is expecting that file to be at a particular path which will be different if you are using a different version of the game.

**Comment by wolfymaster** [comment]
Related to: https://github.com/ottomated/CrewLink/issues/411
