### ISSUE TITLE
[FEATURE] Individual voice sliders

### ISSUE THREAD

**Issue by Jinjubei** [ottomated/CrewLink#435]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [x] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**
It would be nice to adjust peoples volumes. Some people are really loud and others are quiet

**Describe the solution you'd like**
Some point type of volume slider, perhaps when you right-click on someone

**Comment by realwakils** [comment]
This is already in works in #6.
Please make sure to check if your feature has been requested yet.

**Comment by Jinjubei** [comment]
My bad, I did look through and seem to have missed this.
