### ISSUE TITLE
Issues Launching the Mod 

### ISSUE THREAD

**Issue by Xeiality** [ottomated/CrewLink#45]
"Couldn't fech the latest game offsets from the server: http://54.193.94.35:9736/2020.9.22.yml.
This might be because you are on an unsupported version of Among Us.

Restart the app after you fix this."

I have already updated the game to the latest version and I've tried using the public beta to no avail. What shall I do to fix this?

Thanks,
Xei

**Comment by fireflamereed** [comment]
same problem for me

**Comment by KingStrike13** [comment]
Yeah i also have the same problem with the latest version idk what to do

**Comment by LoopedBard3** [comment]
Hello, I looked into the problem a little bit more and it looks like the IP address that was being used for the servers changed. Please try changing the Voice Server IP address from 54.193.94.35 to 209.182.233.230 this should fix this error. This setting can be found both in the crewlink settings and in the config.json file located inside %appdata%/Roaming/crewlink. Please let me know if this worked for you also.

**Comment by HayzeSmokeShop** [comment]
I tried that and it did not work, Neither of the Voice servers are working.

**Comment by WinterElf123** [comment]
This is happening to me as well and idk what to try next

**Comment by nachosthatrpink** [comment]
Hey, there are caveats that the voice servers won't work when a certain number of people are using them. We set up our own and it is working fine.

**Comment by ottomated** [comment]
Host a private server to solve this
