### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Louis-Lesage** [ottomated/CrewLink#461]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ x ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ x ] I am using the Steam version of Among Us
3. [ x ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ x ] I have checked everyone in my lobby is on the same CrewLink server
5. [ x ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ x ] I have checked that the CrewLink server I'm using is up to date
7. [ x ] I have a screenshot of any errors
8. [ x ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

The gui of the crewlink app turn grey and is not responsive when joining a game.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open crewlink app (used https://crewmate.chat/ server)
2. Join a lobby
3. See error

**Expected behaviour**

The gui should show player and options, etc.
**Screenshots**

![image](https://user-images.githubusercontent.com/31346705/103163640-88452500-47ce-11eb-9469-2a0208dcdc34.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.2.0]

**Additional context**

None

**Comment by ottomated** [comment]
Support is only provided for the official server.
