### ISSUE TITLE
[BUG REPORT] 1.2 - Additional Users unable to join, crashes Crew Link

### ISSUE THREAD

**Issue by dustinlynch** [ottomated/CrewLink#462]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spam:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [X] I have checked everyone in my lobby is on the same CrewLink server
5. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [X] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
An admin can successfully create a new room and be connected to a Crew Link server. When all other users join their Crew Link blanks out/freezes. The admin sees a "wifi" disconnected icon.

**To Reproduce**
1. Admin creates a room as normal
2. Additional User opens Crew link and joins the room.

**Expected behavior**
Users to join without the crew link freezing.

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [1.2 Crew Link]

**Additional context**

Not sure how to check the server version but I used the Deploy to Heroku button located at https://github.com/ottomated/CrewLink-server at 2020-12-27 02:49:06 UTC

Admin sees the following:
![Screenshot_2](https://user-images.githubusercontent.com/5107912/103163829-e53ddc80-47c8-11eb-9f32-94280bb540d7.png)

Crew sees the following:
![image](https://user-images.githubusercontent.com/5107912/103163841-fab30680-47c8-11eb-8ff8-371e1ad54c9d.png)

Desktop software
(Admin) ![image](https://user-images.githubusercontent.com/5107912/103163855-28984b00-47c9-11eb-8f43-214ec6dafd92.png)

(Crew)
![image](https://user-images.githubusercontent.com/5107912/103163876-64cbab80-47c9-11eb-9d04-cd6189de34e3.png)

**Comment by toriannwin** [comment]
My group is having this same issue. It seems to work when I host the game, but when someone joins their CrewLink goes blank and on my side it shows them as disconnected.

**Comment by dustinlynch** [comment]
Ah forgot to list the alt server we tried: https://s1.crewlink.de/

**Comment by Quantumrage10** [comment]
same issue with 1.2.0. can't describe it better

**Comment by martinblim** [comment]
Hope this works with the problem... some problem with the code perhaps?

![image](https://user-images.githubusercontent.com/72779942/103165863-e66a1a80-4857-11eb-9cbe-2b4484c96df6.png)

**Comment by dustinlynch** [comment]
@martinblim - How did you do that? I am not familiar with TypeScript. I prefer me some ancient PHP.

**Comment by martinblim** [comment]
@dustinlynch , just pressed CTRL+SHIFT+I (i) on the crewlink app. I don't know the deep code tho... But previous commit history tells some changes on this part of the code.

**Comment by ottomated** [comment]
Someone's on an outdated client or you're on an outdated server.

**Comment by RemyRobert** [comment]
Is the https://crewl.ink server on 1.1.6 or 1.2.0 ? I have the same issue
