### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by pottsykid** [ottomated/CrewLink#465]
I was in crewlink with a group. I was on the same server as everyone, the green circle showed that I was talking and I tested my speakers and could hear clearly, however, no one could hear me and I couldn't hear anyone else. I tried pressing the mute and deafen buttons to see if it would help and it didn't even bring up an icon showing it was deafened or muted. We tried restarting, we tried changing hosts, we tried changing crewlink servers and nothing worked. I tried reinstalling crewlink and among us neither of which worked. All of us in the group were confused as to what happened and eventually gave up. The group was able to keep playing without me.

**Comment by Marcelo-L** [comment]
Having the same issue with someone on our server, Anyone managed to fix this? Made sure drivers are all up to date too

**Comment by dertrockx** [comment]
I don't see a fix here, how come this was closed?
