### ISSUE TITLE
[BUG REPORT] CrewLink "Waiting for Among Us"

### ISSUE THREAD

**Issue by TheSpringBoy** [ottomated/CrewLink#467]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

The CrewLink v1.2.0 stuck on "Waiting for Among Us".
**To Reproduce**
Steps to reproduce the behaviour:
1. Run CrewLink (v1.2.0)
2. Run AmongUs (v2020.12.9s)
Thats it! just doesn't work.

**Screenshots**

![image](https://user-images.githubusercontent.com/75606783/103168406-a7c66700-483b-11eb-9904-8ad997a957b8.png)

**Desktop:**
 - OS: Windows 10
 - Version: 1.2.0

Does anyone else have this problem?

**Comment by Yesitzme** [comment]
I have the same problem, and when i try to click on ''open game" this shows up
![Sans titre](https://user-images.githubusercontent.com/76435834/103170521-0d6b2100-4845-11eb-9757-b16fa80c76be.png)

**Comment by cody62394** [comment]
You MUST own Among-Us on Steam for it to work. It's $5 just buy it.
