### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by NidhishRAR** [ottomated/CrewLink#484]
whenever i open it and among us, it is struck at a black screen
![{88C28F8D-2E43-47F0-BC08-846092F3F722}](https://user-images.githubusercontent.com/76802532/103395119-735fed00-4b52-11eb-98d4-81988fa9facf.png)

**Comment by oliverbooth** [comment]
I'm also getting this, but with no title bar so no access to settings - can't even close the window.
![image](https://user-images.githubusercontent.com/1129769/103431087-b22d8b80-4bc2-11eb-856f-d78074540b38.png)

**Comment by NidhishRAR** [comment]
ya , this is happening for me when i do not open and open crewlink, then it
crashes.....
