### ISSUE TITLE
[FEATURE] Publicize / formalize releasing branch strategy to recognize contributors on GitHub

### ISSUE THREAD

**Issue by sad-squid** [ottomated/CrewLink#488]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [x] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**

So, recently I made a couple contributions to this project, and I'm noticing that I'm not listed as one of the contributors to the project. I think that as far as OSS goes, it's etiquette to show when people contribute by merging their PRs to the next release branch. It shows publicly when you contribute, and it helps develop your portfolio on the site. 

**Describe the solution you'd like**

Obviously, I think that whatever workflow you want to move forward with is up to y'all, but it's just a little weird (in my opinion) to gain open source contributions but not recognize them by merging to a hidden local branch and not merge to master with the commits. Moving to a more inclusive git workflow so contributions could be public would likely encourage future contribution. 

I don't mean this post to be BM or toxic or whatever, just want to hear perspective on why the current approach is taken and what is preventing a public merge on GH, as opposed to privately merging distinct SHA's which do not provide code authors with credit. 

As someone that was really looking forward to contributing to a project like this, it is a little discouraging :( 

**Additional context**

**Comment by ottomated** [comment]
You're the only case of this, and it's because you can prettier on the whole repo and I didn't want to deal with merge conflicts in every single file.

**Comment by ottomated** [comment]
Also, not to belittle your contribution, but it wasn't really a part of the core source code

**Comment by sad-squid** [comment]
@ottomated I think that's a good enough reason to me, thanks for explaining. I  I just was in the dark as to why it happened - that makes sense to me. I was more concerned it was happening with other PRs. Thanks for clarifying 👍
