### ISSUE TITLE
[FEATURE] Voice Changes very harsh between left and right audio channel

### ISSUE THREAD

**Issue by MoritzLerch** [ottomated/CrewLink#504]
Maybe someone here knows how to implement this: 

I noticed when someone walks past you especially when he/she walks straight from the left to the right the output changes very rough from left to right. Maybe a smooth changes between left and right would be nice. 
So possibly there could be a phase when someone is near you the audio does not go from left to right that hard but rather goes left; left and right; right so you here someone on the left AND right channel.

**Comment by Stogoh** [comment]
If you have any experience with programming and you wanna take a look at the code I would suggest that you try to modify PanNode. The filter is responsible for handling the calculation where another player is. Try modifing the values of this node, you might get the result you expect.

You can find this code snippet in the Voice.tsx file.

`pan.positionZ.setValueAtTime(-0.5, audioContext.currentTime);`

**Comment by MoritzLerch** [comment]
Okay, I'll take a look at it. Started with TypeScript yesterday but have been programming for a few years (mostly Python).
