### ISSUE TITLE
crewlink screen is black when I open among us on epic game

### ISSUE THREAD

**Issue by eliet97** [ottomated/CrewLink#511]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [✔ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [❌ ] I am using the Steam version of Among Us
3. [❌ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [✔ ] I have checked everyone in my lobby is on the same CrewLink server
5. [N/A ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [N/A ] I have checked that the CrewLink server I'm using is up to date
7. [✔ ] I have a screenshot of any errors
8. [✔] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
I have newest version of crewlink but crewlink screen become black after opening among us via epic games, till now I never were able to use crewlink
![Screenshot (8)](https://user-images.githubusercontent.com/61003621/103686143-0952a800-4f97-11eb-95ea-c9eb9d09bd75.png)
![Screenshot (9)](https://user-images.githubusercontent.com/61003621/103686163-12437980-4f97-11eb-8210-2cbd35213493.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. I open crewlink 
2. then I open among us
3. as soon as among us load I see black screen of crewlink

**Expected behaviour**
To be able to see people in  lobby using crewlink and talk to them

**Screenshots**
yes

**Desktop (please complete the following information):**
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎2020-‎08-‎17
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional context**

**Comment by TheSpringBoy** [comment]
Hi,
Currently the software only supports the steam version.
