### ISSUE TITLE
FEATURE: supporting other game store like epic games and windows store

### ISSUE THREAD

**Issue by eliet97** [ottomated/CrewLink#519]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ✔] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [✔ ] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [✔ ] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**
crewlink does not detect the game other than the steam version

**Describe the solution you'd like**
before letting people press open the game, give option to locate among us file like locating the .exe file so game will open using .exe file and detect the game.

**Describe alternatives you've considered**
another solution is asking which version of the game you have and crewlink go to launcher and open the game from laucnher

**Additional context**

**Comment by TheSpringBoy** [comment]
its clone for so much suggestions and there is already PR for this
pls close it
