### ISSUE TITLE
Cannot hear/be heard by others while the can hear each other

### ISSUE THREAD

**Issue by BasedSnake** [ottomated/CrewLink#52]
I have this issue and it persists through the default and my hosted server

![image](https://user-images.githubusercontent.com/72772837/100534532-ee458900-31dd-11eb-878d-eb3a31e09ae3.png)
in this pictures the players hear each other while I cannot talk

**Comment by firetopher** [comment]
me and a friend are having this issue aswell, it seems 1 person in our lobby is the only person that can hear them and the glitched person can only hear them

**Comment by uzervlad** [comment]
Related to/Duplicate of #47

**Comment by ottomated** [comment]
Duplicate of #47
