### ISSUE TITLE
Audio can be heard at random

### ISSUE THREAD

**Issue by franglais** [ottomated/CrewLink#526]
The audio of the dead can be heard by pretty much everyone who is still alive. This happens with both dead can be heard by imposters on and off. This is on v2.0.0

**Comment by JWBB1508** [comment]
This is running client 2.0.0 and the latest server (ottomated/CrewLink-server@2fd0562)

Everything seemed to work normally before we turned haunt on, then in the first haunt game several of us (impostors and innocents, including the host) could hear the dead and also could hear people across the map. Then we turned haunt off and played a game with the same issues.

**Comment by ottomated** [comment]
ctrl+R

**Comment by JWBB1508** [comment]
We just played a different game in a fresh lobby with haunt off from the start, and the host (+ one other player who was an impostor) could hear one specific other player (crewmate) from across the map. When the crewmate died, those two players could also hear him as a ghost. We're using the default voice server if that's helpful.

We've been doing an awful lot of ctrl+R to no avail, and I think it's definitely still an issue if you only realise to ctrl+R after hearing voices from beyond the grave :P
