### ISSUE TITLE
When dead person leaves entire lobby bugs

### ISSUE THREAD

**Issue by TheEx0diac** [ottomated/CrewLink#530]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
<So when someone leaves when dead and in the midst of an ongoing game some people cannot be heard. This is completely random. It also sometimes shows you as dead and as the person who left.>

**To Reproduce**
Steps to reproduce the behaviour:
1. Leave when dead and in a game
2. Error may occur

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Version: [e.g. 1.1.5] 2.0.0

**Additional context**

**Comment by ottomated** [comment]
more details needed
