### ISSUE TITLE
2.0.1 voice server does not support this version

### ISSUE THREAD

**Issue by mackedanzchr** [ottomated/CrewLink#532]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

Error: the voice server does not support your version of crewlink.  Supported versions: 1.2.0,1.2.1,2.0.0

**To Reproduce**
Steps to reproduce the behaviour:
download 2.0.1, get the error.

**Expected behaviour**
it work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by hxndgxns** [comment]
Same issue here. Updated to 2.0.0 and it wouldn't connect anyone in the lobby to voice. Then updated to 2.0.1 and it was throwing an error that the voice server does not support version of crewlink. Then I attempted to connect again, and it wouldn't connect anyone in the lobby to voice again.
