### ISSUE TITLE
Program not starting. A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by GabiruFrito** [ottomated/CrewLink#556]
I was waiting for a version compatible with 32bit, since the previous ones woudnt even instal.
With the version 2.0.1 installed, I tried to start it when this message appeared:

![error](https://user-images.githubusercontent.com/77294661/104222867-a8592300-5421-11eb-98b4-481b7e322e2e.png)

I saw someone with a similar problem, but the message he received was a little bit different and his solution didnt worked for me.
I'm not an expert in the matter, so a step-by-step instruction will help a lot.
Thank you.

**Comment by ottomated** [comment]
Windows 7 isn't even supported by microsoft
