### ISSUE TITLE
Overlay bug

### ISSUE THREAD

**Issue by asdfdsa2** [ottomated/CrewLink#560]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x ] I am using the Steam version of Among Us
3. [x ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x ] I have checked everyone in my lobby is on the same CrewLink server
5. [x ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x ] I have checked that the CrewLink server I'm using is up to date
7. [x ] I have a screenshot of any errors
8. [x ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Overlay doesn't work; I have tried making it hidden and changing it from left/right

**To Reproduce**
Steps to reproduce the behaviour:
1. Open crewlink
2. Open game through crewlink
3. ???
4. profit, jk it's there on game start

**Screenshots**
https://gyazo.com/8fcc7c9fd8bcd02e6545d61bfcf45f13

**Desktop (please complete the following information):**
 - OS: windows 7 ultimate 64 bit
 - Version: SP1
**Additional context**
It has something to do with the overlay feature, It goes away when i close out of crewlink but not among us, I tried running it with windows 7 compatibility and I always run in admin mode. Not sure if it's because of windows 7?

**Comment by ottomated** [comment]
Crewlink is incompatible with win7
