### ISSUE TITLE
Salt AF Dev.

### ISSUE THREAD

**Issue by nfraynor** [ottomated/CrewLink#562]
When noting an issue in a friendly manner that this uses more CPU than most games simply for voice chat the dev got super salty and banned me for simply saying that it uses a lot of CPU. To note, 60% on a i7-9750. 

Perhaps he should not be a salty bitch?

Dude, your latest update broke this and I just wanted to give you a heads up about the issue, If you can't handle that, then at least don't be a dick.

**Comment by ottomated** [comment]
The fact that you opened a GitHub issue about this speaks for itself. I'm blocking you from this repo not only for spreading misinformation, but using a bug report to do it.
