### ISSUE TITLE
Fatal crash on Windows 7: No native build was found for platform=wind32 ...

### ISSUE THREAD

**Issue by sim590** [ottomated/CrewLink#580]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [N/A] I am using the Steam version of Among Us
3. [N/A] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [N/A] I have checked everyone in my lobby is on the same CrewLink server
5. [N/A] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [N/A] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

Fatal crash when opening the App on Windows 7.

![nonativebuildwasfound](https://user-images.githubusercontent.com/4147254/104824460-ca86e280-581f-11eb-80c9-c1df2318d923.png)

**To Reproduce**

1. Download the release `.exe` file (I did download the latest 2.0.1 build).
2. Run the installer.
3. Open the App and see the error when launching.

**Expected behaviour**

No crash when running the only executable file that is said to be needed to install the program...

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: **I will provide it shortly**

**Comment by Pouidesbois** [comment]
Try to check Task Manager and close all CrewLink instances then try to open it again ! it works fine for me like that

**Comment by OhMyGuus** [comment]
Offical Crewlink doesn't support 32 bit anymore, you can try [this](https://github.com/OhMyGuus/BetterCrewLink/releases)

**Comment by sim590** [comment]
@OhMyGuus you're right. That's the issue. We have 32 bit installation. Since there are other issues opened about this (#426, #436, #61, #233, #240, #265, #405, #516, #549) I will close this one.
