### ISSUE TITLE
Proximity Text Chat

### ISSUE THREAD

**Issue by BeeFox-sys** [ottomated/CrewLink#589]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [x] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**
My friends and I would like to play proximity among us, however I am mute and as such cannot use crewlink and am left at a disadvantage.

**Describe the solution you'd like**
Ideally, some sort of text bubble would appear, either on the edge of the screen (if the player is off screen) or above the player, possibly changing size based on distance (similar to the volume changing based on distance)
I do understand if this would require too much modification to the game, in which case maybe some chat window in the crew link application that only sends to people close enough to "hear"

**Describe alternatives you've considered**
I have considered a simple discord channel or something like that however then everyone can see the messages no matter where on the map

**Comment by ottomated** [comment]
This is unfortunately out of scope for this project.
