### ISSUE TITLE
Installation executable picked up by Kaspersky as a virus

### ISSUE THREAD

**Issue by ppzjdp** [ottomated/CrewLink#60]
![image](https://user-images.githubusercontent.com/69046752/100550755-07991480-3274-11eb-91c6-f2e164e7de0a.png)

![image](https://user-images.githubusercontent.com/69046752/100551983-23081d80-327c-11eb-97c9-16ec724db8fd.png)

Chrome stated there was a virus detected, Kaspersky indicates an AMSI stream was detected. Could someone with better knowledge explain why this happens?

**Comment by ottomated** [comment]
iohook and memoryjs
