### ISSUE TITLE
Error : couldn't connect to your microphone

### ISSUE THREAD

**Issue by Rxmrln** [ottomated/CrewLink#630]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
I downloaded the new version of crew link and when opening crew link and trying to open among us I had an error : couldn't connect to your microphone

**To Reproduce**
Steps to reproduce the behaviour:
1. Download CrewLink 
2. Launch crewlink
3. Click on open game

**Expected behaviour**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/81491940/112735693-3c7d5580-8f4e-11eb-93a5-b9305dab90e9.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version: 2.4.0

**Comment by MatadorProBr** [comment]
This is a bug that has to do with BetterCrewLink not with CrewLink, if the bug continues please report it by [clicking here](https://github.com/OhMyGuus/BetterCrewLink/issues) for the official BetterCrewLink project issues
