### ISSUE TITLE
Voice Server IP not letting me enter

### ISSUE THREAD

**Issue by sashman2013** [ottomated/CrewLink#65]
I have been trying to set up a private server for this and I am not able to enter an IP (or any type-in prompt for that matter) after I come up with the error message stating I need to fix my IP and to restart after fixing. Well I cant fix it because of that. Please help

**Comment by sashman2013** [comment]
I am able to type stuff in right up until the error prompt which appears before I have the chance to type anything in. (about 2 seconds) Afterwards I am unable to type anything in.

**Comment by cgannaway** [comment]
Try tabbing out of the window and tabbing back in after you are unable to type. Weird fix but it worked for my friends.
