### ISSUE TITLE
bug cant hear sertin ppl

### ISSUE THREAD

**Issue by Littlemac123** [ottomated/CrewLink#76]
how can i report a bug i get where i can only hear Stanza and JD Dark but 8 other people in the call i cant hear at all but everyone else hears them.

and I only hear them threw echos of stanza or JD mic

**Comment by Littlemac123** [comment]
i been using this mod for 3 days and i uninstalled and re installed 6 times no fix

**Comment by Littlemac123** [comment]
as well as Ctrl R

**Comment by ottomated** [comment]
Duplicate
