### ISSUE TITLE
Messes up sound system wide and is dependent on NAT type for functionality

### ISSUE THREAD

**Issue by NC1107** [ottomated/CrewLink#77]
I would recommend making an individual slider for the voice input and output volume for individual players to set because everyone's audio setup is different. it also makes people either extremely loud or extremely quiet outside of the game such as in discord and requires a restart and manual adjustments to revert to normal.  users with strict NAT's are unable to hear people that don't have an open NAT type, so if you are unable to hear the entire party or can only hear one person it's quite likely they have an open NAT type and you have a strict NAT type.

**Comment by ottomated** [comment]
Open NAT is required for p2p and volume settings are in the works
