### ISSUE TITLE
Game detected but lobby not detected

### ISSUE THREAD

**Issue by WolfDWyc** [ottomated/CrewLink#79]
My among us game is detected (can see that is says "menu"):
![image](https://user-images.githubusercontent.com/62406166/100751958-a9457080-33f0-11eb-9d0b-5a28176322b1.png)
But my lobbies aren't detected:
![image](https://user-images.githubusercontent.com/62406166/100752004-b7938c80-33f0-11eb-9a6a-6c0c10c8087d.png)

- Tried with versions v1.0.4 and v1.1.2
- Tried with an heroku server or the default one.
- Tried joining public lobbies or creating my own.
- Running Windows 10.
- Not running the steam version.

**Comment by YOYITsM3M8** [comment]
Non steam version doesn't work

**Comment by WolfDWyc** [comment]
Thanks!
