### ISSUE TITLE
Suggestion: Comms sabotage mutes mics

### ISSUE THREAD

**Issue by SamWidenbar** [ottomated/CrewLink#80]
It'd be cool if when comms was sabotaged, the CrewLink cut chat between the living crewmates; either mics muted, and maybe deafened too so impostors can talk amongst themselves while comms are out.

Comms would finally be useful.

**Comment by ottomated** [comment]
Duplicate

**Comment by heptacat-storm** [comment]
Duplicate is not a copy all the time. When i am trying to make levogir
movement in Lx~Lx, one of this knot is not visible and is called etheral
knot. In this case you need to initiate a middle knot. Life is about 3,
where 3 is the prime line. Without the middle knot you can't to something
without errors. And the middle knot is the definition of good sense in
everything.
So, Matrix can also suck the reality about duplicate.
So, the middle knot is the answer.

**Comment by SamWidenbar** [comment]
Issue #7 about customizable lobby settings mentions this, for anyone else wondering where the duplicate is. Also sounds like it would be a good idea to make it an option, so that's a good place for it to live.
