### ISSUE TITLE
Custom game path selector/setting

### ISSUE THREAD

**Issue by Lavodan** [ottomated/CrewLink#82]
**Add an option to select a custom path for the game**

As I use an external drive for all of my games, CrewLink does not recognize Among Us as being installed (Or rather, its telling me that it "could not fetch the latest game offsets")

To be specific, by _"custom path selector,"_ I mean an option in the settings, that is by default (I'm guessing since I could not find this in the code anywhere, but I'm a github noob) `%ProgramFiles(x86)%\Steam\steamapps\common\Among Us` for windows, but could be changed to really anything, say `E:\Games\steamapps\common\Among Us` or even `C:\Users\%currentuser%\Desktop\Games\steamapps\common\Among Us`

**Comment by heptacat-storm** [comment]
I have a question: how is better to hack NianticLabs? Legal way or encrypt
in ensõ language?

**Comment by Lavodan** [comment]
> 
> 
> **Add an option to select a custom path for the game**
> 
> As I use an external drive for all of my games, CrewLink does not recognize Among Us as being installed (Or rather, its telling me that it "could not fetch the latest game offsets")
> 
> To be specific, by _"custom path selector,"_ I mean an option in the settings, that is by default (I'm guessing since I could not find this in the code anywhere, but I'm a github noob) `%ProgramFiles(x86)%\Steam\steamapps\common\Among Us` for windows, but could be changed to really anything, say `E:\Games\steamapps\common\Among Us` or even `C:\Users\%currentuser%\Desktop\Games\steamapps\common\Among Us`

Just noticed #14

**Comment by Lavodan** [comment]
> 
> I have a question: how is better to hack NianticLabs? Legal way or encrypt in ensõ language?

What the hell are you talking about?

**Comment by nailuj29gaming** [comment]
@Lavodan I'm just as confused as you are

**Comment by Sxxov** [comment]
From my limited scouring of the codebase, CrewLink seems to be install directory independent, as it does all it's hooking from memory. That [error](https://github.com/ottomated/CrewLink/blob/13f6bc5c0c71b276608e1c00859e0630cdc44f41/src/main/hook.ts#L80) should point to it already recognizing the version of among us installed and then failing when trying to grab the premade offsets. Not sure why it's failing though, since yours is a steam build, unless it's an old version not listed [here](https://github.com/ottomated/CrewLink-server/tree/master/offsets).

**Comment by Lavodan** [comment]
@Sxxov Wow, you're completely right, I misunderstood the code completely; my problem was that I hadn't run the game since updating; its interesting how it doesn't need the directory and instead grabs it from memory, so yeah, my suggestion doesn't even make sense with how this app works, thank you very much!

**Comment by heptacat-storm** [comment]
You can code, remember, until the code was the font and i can introduce
font in everything. All i need is the link, but the crew is working on it.

**Comment by Sxxov** [comment]
@Lavodan Glad I could help!
