### ISSUE TITLE
Hearing everyone in robotic voices

### ISSUE THREAD

**Issue by FleXCrash** [ottomated/CrewLink#86]
Very likely a specific issue for me personally, but I figured I'd make an issue for it.
I launched the game with 2 different friends. Both of them can hear me as crisp as I am in Discord, however their voices sound like the typical bad connection robot voice for me only.
I am running a fairly beasty setup with a 200Mbs connection. No downloads going on or clogged up CPU/RAM/Disk usage.

Again likely a personal issue, but throwing it in here anyway to see if others also experience it.

Also, you are doing an amazing job mate! It's amazing to see what people can create for such a popular game.

//Edit
I also ran a local server on my own pc on which I let my friends join. Same problem.

**Comment by CheckisCheck** [comment]
Is this as they are joining or through the whole game?

**Comment by FleXCrash** [comment]
Throughout the whole game.
This is not the typical leaving the game and going into a lobby, robotic voice.

**Comment by Peteledete** [comment]
I have this issue, but none of the other players on the same server have the issue. Maybe it's an issue with audio drivers? It sounds like its bigtime lag, so maybe its clientside. But I feel like I'd have that issue in discord as well as other games, but I don't.

**Comment by FleXCrash** [comment]
Yeah exactly. Discord is fine, just Crewlink seems to be struggling. Tonight I'll give the latest version a try.

**Comment by FleXCrash** [comment]
I made a little recording so you can see what I am hearing during the game.
https://drive.google.com/file/d/1JsII3lNxtnZTbe2GQ6PBT7IaNpb3xIcE/view

**Comment by FleXCrash** [comment]
Given a few people got the same issue, I am going to put some pc specs in here:
X570 AORUS ULTRA
AMD Ryzen 7 3800x
32GB DDR4
MSI GTX 1070

**Comment by DiamondFluxify** [comment]
I have the same issue, a fair bit worse than the clip you posted but similar situation
Specs:
AMD Ryzen 7 2700
Powercolor Vega 64
MSI B450 Tomahawk
16GB DDR4 3200MHz

**Comment by siaruchiha** [comment]
I had the exact same Problem and fixed it by installing the previous Audio driver.

**Comment by DiamondFluxify** [comment]
> 
> 
> I had the exact same Problem and fixed it by installing the previous Audio driver.

What version did you install do you know? I'm on 6.00.0001.8366 I believe

**Comment by FleXCrash** [comment]
Yup worked for me as well. I noticed my audio output was not recognized properly. Even though the sound was just fine.

Check if your audio device is under "Other Devices" and if so, download the appropriate driver for it, so it is properly listed under "Audio inputs and outputs".

Hope this helps you @DiamondFluxify @Peteledete and @Ecnivate

**Comment by DiamondFluxify** [comment]
Well it didn't since I'm already on the newest version according to Realtek and Windows, which is why I asked what version people have installed who fixed their problem

**Comment by DiamondFluxify** [comment]
> 
> 
> Yup worked for me as well. I noticed my audio output was not recognized properly. Even though the sound was just fine.
> 
> Check if your audio device is under "Other Devices" and if so, download the appropriate driver for it, so it is properly listed under "Audio inputs and outputs".
> 
> ![image](https://user-images.githubusercontent.com/17702621/101349021-ec8a5e00-388c-11eb-9a61-3f4eadf24b78.png)
> Control panel > Hardware and Sound > Device manager
> 
> Hope this helps you @DiamondFluxify @Peteledete and @Ecnivate

What version did you install? I'm on the newest version according to Windows and Realtek

**Comment by FleXCrash** [comment]
I'm not using Realtek...
I installed a driver for my Ifi DAC, which has nothing to do with Realtek. Try to see if there are specific drivers for your headphones.

**Comment by gbrldz** [comment]
> I'm not using Realtek...
> I installed a driver for my Ifi DAC, which has nothing to do with Realtek. Try to see if there are specific drivers for your headphones.

I have the same exact issue. I have the iFi ZEN DAC. Did you update or downgrade your driver?

**Comment by FleXCrash** [comment]
> > I'm not using Realtek...
> > I installed a driver for my Ifi DAC, which has nothing to do with Realtek. Try to see if there are specific drivers for your headphones.
> 
> I have the same exact issue. I have the iFi ZEN DAC. Did you update or downgrade your driver?

Updates I guess.
I was running on the Windows driver. Installed the latest one from their website and it was all fixed.

**Comment by gbrldz** [comment]
> > > I'm not using Realtek...
> > > I installed a driver for my Ifi DAC, which has nothing to do with Realtek. Try to see if there are specific drivers for your headphones.
> > 
> > 
> > I have the same exact issue. I have the iFi ZEN DAC. Did you update or downgrade your driver?
> 
> Updates I guess.
> I was running on the Windows driver. Installed the latest one from their website and it was all fixed.

Aww damnit. I'm running on the latest provided by iFi and getting the static.

**Comment by FleXCrash** [comment]
Not sure if it helps, but I am running driver version 10.0.18362.1 (Ifi Zen Dac that is)

**Comment by TracerYT** [comment]
I have that problem too but I have the newest audio drivers

**Comment by siaruchiha** [comment]
> I have that problem too but I have the newest audio drivers

idk if u still have the problem but i didnt install a newer but an older driver

**Comment by DiamondFluxify** [comment]
> idk if u still have the problem but i didnt install a newer but an older driver

What version?

**Comment by ToastyStoemp** [comment]
We had someone with a similar issue, and for them turning off spatial sounds fixed the issue version 1.1.6

**Comment by AlwaysStijn** [comment]
i have the same issue, and it's getting worse and worse, used to be 1/5 games and now it's the moment i join the game.
i've tried updating my logitech drivers (have the g933)  and turning off the surround sound but nothing is helping.
any tips or help would be appreciated.

**Comment by FrankRidder** [comment]
> i have the same issue, and it's getting worse and worse, used to be 1/5 games and now it's the moment i join the game.
> i've tried updating my logitech drivers (have the g933) and turning off the surround sound but nothing is helping.
> any tips or help would be appreciated.

I have the exact same issue with the same headset. Have you found a solution?

**Comment by Stig2** [comment]
Had this problem on my machine, fixed it by turning down the audio quality in my Realtek Audio Manager from 24bit/192kHz to 24bit/96kHz.

**Comment by Tschyp** [comment]
> Had this problem on my machine, fixed it by turning down the audio quality in my Realtek Audio Manager from 24bit/192kHz to 24bit/96kHz.

Confirmed. Same for me. 

![image](https://user-images.githubusercontent.com/17083181/104780697-73323500-5781-11eb-849a-1b75d7915d3e.png)


(I just reseted my password to be able to log in and write the same. But you already solved the case :D)

**Comment by AndiBuzer** [comment]
Can confirm that two. Got an Asus Essence STX II and resetting the audio quality to 24bit and 48000 Hz fixes the distortion. Is there a possibility to patch this?

**Comment by GandalfTheWhite80** [comment]
Same Problem here - 16bit/48.000Hz :-(
