### ISSUE TITLE
Doesn't work with wine (Linux's way of playing window only games)

### ISSUE THREAD

**Issue by YaseenFSD** [ottomated/CrewLink#98]
Doesn't work with wine (Linux's way of playing windows only games)

![Screenshot from 2020-12-03 16-25-54](https://user-images.githubusercontent.com/61301657/101090918-6537a480-3585-11eb-87cc-51f3dcdb8547.png)

**Comment by ottomated** [comment]
Duplicate

**Comment by C0rn3j** [comment]
Duplicate of #4 to be exact, since I was looking for it.
