### ISSUE TITLE
Kaspersky antivirus detects the setup as a virus and deletes upon download

### ISSUE THREAD

**Issue by Floffah** [ottomated/CrewLink#99]
even when adding it to exclusions or ignore it still deletes it
![image](https://user-images.githubusercontent.com/27270386/101093348-8367c980-35b2-11eb-9447-7bc410cc1914.png)

**Comment by crashbrocksta** [comment]
i googled it, and this trojan is a keylogger, a virus that registers all your keystrokes and potentially mouse movements, if you have the file installed i recommend doing a full scan of your pc with your antivirus software, this isn't the developers fault, they probably had nothing to do with this. it's simply the fact that github is terribly secured and hackers can easily corrupt the download files on here.

**Comment by vb-03** [comment]
Can confirm, showing as Trojan-Spy.Win32.Xegumumune.fkc

**Comment by ottomated** [comment]
Disable it, false positive.
